# Generated by Django 2.2.3 on 2019-07-05 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telefon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_sex', models.CharField(choices=[('Pan', 'Pan'), ('Pani', 'Pani')], default='Pan', max_length=100, verbose_name='Płeć')),
                ('usr', models.CharField(max_length=100, verbose_name='Użytkownik')),
                ('model', models.CharField(max_length=200, verbose_name='Model telefonu')),
                ('imei', models.CharField(max_length=200, verbose_name='IMEI telefonu')),
                ('sim', models.CharField(blank=True, max_length=200, verbose_name='Nr karty SIM')),
                ('msisdn', models.CharField(blank=True, max_length=200, verbose_name='Nr MSISDN')),
                ('kod', models.CharField(blank=True, max_length=200, verbose_name='Kod Blokady')),
                ('konto', models.CharField(blank=True, max_length=200, verbose_name='Konto')),
                ('haslo', models.CharField(blank=True, max_length=200, verbose_name='Hasło')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data przekazania')),
                ('uwagi', models.TextField(blank=True, verbose_name='Uwagi')),
            ],
            options={
                'verbose_name': 'Telefon',
                'verbose_name_plural': 'Telefony',
            },
        ),
    ]
