# Generated by Django 2.2.3 on 2020-02-09 04:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PHONES', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefon',
            name='arch',
            field=models.BooleanField(default=False, verbose_name='Konfiguracja Archiwalna'),
        ),
        migrations.AddField(
            model_name='telefon',
            name='doc',
            field=models.FileField(blank=True, upload_to='dokuments', verbose_name='Dokument przyjęcia'),
        ),
        migrations.AddField(
            model_name='telefon',
            name='docz',
            field=models.FileField(blank=True, upload_to='dokuments', verbose_name='Dokument zdania'),
        ),
        migrations.AddField(
            model_name='telefon',
            name='pesel',
            field=models.CharField(blank=True, max_length=100, verbose_name='PESEL'),
        ),
        migrations.AddField(
            model_name='telefon',
            name='pz',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data zdania'),
        ),
        migrations.AddField(
            model_name='telefon',
            name='zam',
            field=models.CharField(blank=True, max_length=300, verbose_name='Zamieszkały'),
        ),
    ]
