# Generated by Django 2.2.3 on 2020-02-09 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PHONES', '0002_auto_20200209_0450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefon',
            name='usr_sex',
        ),
    ]
