# Generated by Django 2.2.3 on 2020-04-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHONES', '0003_remove_telefon_usr_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefon',
            name='mag',
            field=models.BooleanField(default=False, verbose_name='Magazyn'),
        ),
    ]
