# Generated by Django 3.1.3 on 2022-01-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHONES', '0004_telefon_mag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefon',
            name='doc',
            field=models.FileField(blank=True, upload_to='protokoly', verbose_name='Dokument przyjęcia'),
        ),
        migrations.AlterField(
            model_name='telefon',
            name='docz',
            field=models.FileField(blank=True, upload_to='protokoly', verbose_name='Dokument zdania'),
        ),
    ]
