# Generated by Django 3.1.3 on 2022-06-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHONES', '0005_auto_20220104_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefon',
            name='bkod',
            field=models.BooleanField(default=False, verbose_name='Brak kodu blokady'),
        ),
    ]
