# Generated by Django 3.1.3 on 2024-04-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHONES', '0013_alter_telefon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefon',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
