# Generated by Django 2.2.3 on 2020-01-06 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubezpieczenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200, verbose_name='Nazwa/Nr Polisy')),
                ('dotyczy', models.CharField(max_length=200, verbose_name='Czego/kogo dotyczy')),
                ('opiekun', models.CharField(max_length=100, verbose_name='Opiekun (Imię i Nazwisko)')),
                ('skn1', models.FileField(blank=True, upload_to='dokuments', verbose_name='Skan1')),
                ('skn2', models.FileField(blank=True, upload_to='dokuments', verbose_name='Skan2')),
                ('daod', models.DateField(default=django.utils.timezone.now, verbose_name='Data od')),
                ('dado', models.DateField(default=django.utils.timezone.now, verbose_name='Data do')),
                ('uwagi', models.TextField(blank=True, verbose_name='Uwagi')),
            ],
            options={
                'verbose_name': 'Ubezpieczenie',
                'verbose_name_plural': 'Ubezpieczenia',
            },
        ),
    ]
