# Generated by Django 3.1.3 on 2022-01-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INSURANCE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubezpieczenie',
            name='skn1',
            field=models.FileField(blank=True, upload_to='insurance', verbose_name='Skan1'),
        ),
        migrations.AlterField(
            model_name='ubezpieczenie',
            name='skn2',
            field=models.FileField(blank=True, upload_to='insurance', verbose_name='Skan2'),
        ),
    ]
