# Generated by Django 3.1.3 on 2022-05-28 22:10

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('INSURANCE', '0002_auto_20220104_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ubezpieczenie',
            old_name='dado',
            new_name='data_do',
        ),
        migrations.RenameField(
            model_name='ubezpieczenie',
            old_name='daod',
            new_name='data_od',
        ),
        migrations.RemoveField(
            model_name='ubezpieczenie',
            name='opiekun',
        ),
        migrations.RemoveField(
            model_name='ubezpieczenie',
            name='skn1',
        ),
        migrations.RemoveField(
            model_name='ubezpieczenie',
            name='skn2',
        ),
        migrations.AddField(
            model_name='ubezpieczenie',
            name='data_raty',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data raty'),
        ),
        migrations.AddField(
            model_name='ubezpieczenie',
            name='doc1',
            field=models.FileField(blank=True, upload_to='insurance', verbose_name='Dokument 1'),
        ),
        migrations.AddField(
            model_name='ubezpieczenie',
            name='doc2',
            field=models.FileField(blank=True, upload_to='insurance', verbose_name='Dokument 2'),
        ),
        migrations.AddField(
            model_name='ubezpieczenie',
            name='firma',
            field=models.CharField(default='', max_length=200, verbose_name='Firma'),
        ),
        migrations.AddField(
            model_name='ubezpieczenie',
            name='raty',
            field=models.BooleanField(default=False, verbose_name='Raty'),
        ),
        migrations.AddField(
            model_name='ubezpieczenie',
            name='suma',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Suma ubezpieczenia'),
        ),
        migrations.AddField(
            model_name='ubezpieczenie',
            name='suma_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='ubezpieczenie',
            name='dotyczy',
            field=models.CharField(default='', max_length=200, verbose_name='Przedmiot ubezpieczenia'),
        ),
        migrations.AlterField(
            model_name='ubezpieczenie',
            name='nazwa',
            field=models.CharField(default='', max_length=200, verbose_name='Nr Polisy'),
        ),
    ]
