# Generated by Django 3.1.3 on 2022-05-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INSURANCE', '0003_auto_20220528_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubezpieczenie',
            name='rodzaj',
            field=models.CharField(choices=[('Ubezpieczenie', 'Ubezpieczenie'), ('Inne', 'Inne')], default='Ubezpieczenie', max_length=100, verbose_name='Rodzaj dokumentu'),
        ),
    ]
