# Generated by Django 3.1.3 on 2022-05-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INSURANCE', '0004_ubezpieczenie_rodzaj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubezpieczenie',
            name='data_raty',
            field=models.DateField(blank=True, verbose_name='Data raty'),
        ),
    ]
