# Generated by Django 3.1.3 on 2022-05-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INSURANCE', '0005_auto_20220529_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubezpieczenie',
            name='data_raty',
            field=models.DateField(blank=True, null=True, verbose_name='Data raty'),
        ),
    ]
