# Generated by Django 3.1.3 on 2022-05-30 11:10

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('INSURANCE', '0006_auto_20220529_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Termin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.CharField(default='', max_length=200, verbose_name='Firma')),
                ('nazwa', models.CharField(default='', max_length=200, verbose_name='Nr Polisy')),
                ('dotyczy', models.CharField(default='', max_length=200, verbose_name='Opis')),
                ('suma_currency', djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3)),
                ('suma', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Suma ubezpieczenia')),
                ('skladka_currency', djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3)),
                ('skladka', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Skladka')),
                ('doc1', models.FileField(blank=True, upload_to='insurance', verbose_name='Dokument 1')),
                ('doc2', models.FileField(blank=True, upload_to='insurance', verbose_name='Dokument 2')),
                ('data_od', models.DateField(default=django.utils.timezone.now, verbose_name='Data od')),
                ('data_do', models.DateField(default=django.utils.timezone.now, verbose_name='Data do')),
                ('raty', models.BooleanField(default=False, verbose_name='Raty')),
                ('data_raty', models.DateField(blank=True, null=True, verbose_name='Data raty')),
                ('uwagi', models.TextField(blank=True, verbose_name='Uwagi')),
            ],
            options={
                'verbose_name': 'Termin',
                'verbose_name_plural': 'Terminy',
            },
        ),
        migrations.AddField(
            model_name='ubezpieczenie',
            name='skladka',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Skladka'),
        ),
        migrations.AddField(
            model_name='ubezpieczenie',
            name='skladka_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
    ]
