# Generated by Django 3.1.3 on 2022-05-30 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INSURANCE', '0007_auto_20220530_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termin',
            name='data_raty',
        ),
        migrations.RemoveField(
            model_name='termin',
            name='nazwa',
        ),
        migrations.RemoveField(
            model_name='termin',
            name='raty',
        ),
    ]
