# Generated by Django 3.1.3 on 2023-04-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INSURANCE', '0009_auto_20230402_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubezpieczenie',
            name='stu',
            field=models.IntegerField(default=0, verbose_name='Status ubezpieczenia '),
        ),
    ]
