# Generated by Django 3.1.3 on 2023-04-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INSURANCE', '0010_ubezpieczenie_stu'),
    ]

    operations = [
        migrations.AddField(
            model_name='termin',
            name='stt',
            field=models.IntegerField(default=0, verbose_name='Status terminu '),
        ),
    ]
