# Generated by Django 5.0 on 2023-12-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INSURANCE', '0013_alter_termin_id_alter_ubezpieczenie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termin',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ubezpieczenie',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
