# Generated by Django 2.2.3 on 2020-01-06 15:37

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faktura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data zgłoszenia')),
                ('imie', models.CharField(max_length=100, verbose_name='Imię')),
                ('nazwisko', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('rfaktura', models.CharField(choices=[('PROFORMA', 'PROFORMA'), ('ZALICZKOWA', 'ZALICZKOWA'), ('ROZLICZAJACA', 'ROZLICZAJĄCA'), ('KOREKTA', 'KOREKTA'), ('INNE', 'INNE')], default='PROFORMA', max_length=100, verbose_name='Rodzaj faktury')),
                ('termin', models.DateField(default=django.utils.timezone.now, verbose_name='Termin płatności')),
                ('targi', models.CharField(max_length=200, verbose_name='Nazwa Targów')),
                ('stoisko', models.CharField(max_length=200, verbose_name='Nazwa Stoiska')),
                ('kwota_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar\xa0Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski Nowy')], default='PLN', editable=False, max_length=3)),
                ('kwota', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Kwota [ netto ]')),
                ('zaco', models.CharField(choices=[('STOISKO', 'STOISKO'), ('PROJEKT', 'PROJEKT STOISKA'), ('MAGAZYNOWANIE', 'MAGAZYNOWANIE'), ('TRANSPORT', 'TRANSPORT')], default='STOISKO', max_length=100, verbose_name='Za co')),
                ('spec', models.CharField(choices=[('NIE', 'NIE MA'), ('TAK', 'JEST')], default='NIE', max_length=20, verbose_name='Specyfikacja')),
                ('uwagi', models.TextField(blank=True, verbose_name='Uwagi')),
                ('zrobione', models.BooleanField(default=False, verbose_name='Wystawione')),
            ],
            options={
                'verbose_name': 'Faktura',
                'verbose_name_plural': 'Faktury',
            },
        ),
    ]
