# Generated by Django 2.2.3 on 2020-01-14 06:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('INVOICES', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktura',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data zgłoszenia'),
        ),
    ]
