# Generated by Django 3.1.3 on 2021-08-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVOICES', '0004_auto_20201228_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='faktura',
            name='sig_source',
            field=models.BooleanField(default=False),
        ),
    ]
