# Generated by Django 3.1.3 on 2022-01-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVOICES', '0005_faktura_sig_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='faktura',
            name='confirm',
            field=models.CharField(choices=[('SKYPE', 'SKYPE'), ('E-MAIL', 'E_MAIL'), ('BEZ POTWIERDZENIA', 'BEZ POTWIERDZENIA')], default='SKYPE', max_length=50, verbose_name='Potwierdzenie'),
        ),
        migrations.AddField(
            model_name='faktura',
            name='naz_imie',
            field=models.CharField(choices=[('Agnieszka Skóra', 'Agnieszka Skóra'), ('Julia Królak', 'Julia Królak'), ('Piotr Junik', 'Piotr Junik'), ('Dariusz Kaczmarek', 'Dariusz Kaczmarek'), ('Łukasz Jerzmanowski', 'Łukasz Jerzmanowski'), ('Michał Ogrzewalski', 'Michał Ogrzewalski'), ('Marzena Michalska', 'Marzena Michalska'), ('Łukasz Zaremba', 'Łukasz Zaremba'), ('Joanna Dittmar', 'Joanna Dittmar'), ('Adam Beim', 'Adam Beim'), ('Eryk Przybyłowicz', 'Eryk Przybyłowicz'), ('Małgosia Świadek', 'Małgosia Świadek')], default='', max_length=500, verbose_name='Imię i Nazwisko'),
        ),
        migrations.AlterField(
            model_name='faktura',
            name='imie',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='faktura',
            name='nazwisko',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nazwisko'),
        ),
    ]
