# Generated by Django 3.1.3 on 2022-01-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVOICES', '0007_auto_20220107_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Osoby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naz_imie', models.CharField(max_length=300, verbose_name='Imię i Nazwisko')),
                ('skype', models.CharField(max_length=200, verbose_name='Adres Skype')),
                ('email', models.CharField(max_length=200, verbose_name='Adres e-mail')),
            ],
            options={
                'verbose_name': 'Osoba',
                'verbose_name_plural': 'Osoby',
            },
        ),
        migrations.AlterField(
            model_name='faktura',
            name='naz_imie',
            field=models.CharField(choices=[('', ''), ('Agnieszka Skóra', 'Agnieszka Skóra'), ('Julia Królak', 'Julia Królak'), ('Piotr Junik', 'Piotr Junik'), ('Laura Bartkowiak', 'Laura Bartkowiak'), ('Dariusz Kaczmarek', 'Dariusz Kaczmarek'), ('Łukasz Jerzmanowski', 'Łukasz Jerzmanowski'), ('Michał Ogrzewalski', 'Michał Ogrzewalski'), ('Marzena Michalska', 'Marzena Michalska'), ('Łukasz Zaremba', 'Łukasz Zaremba'), ('Joanna Dittmar', 'Joanna Dittmar'), ('Adam Beim', 'Adam Beim'), ('Eryk Przybyłowicz', 'Eryk Przybyłowicz'), ('Małgosia Świadek', 'Małgosia Świadek')], default='', max_length=300, verbose_name='Imię i Nazwisko'),
        ),
    ]
