# Generated by Django 3.1.3 on 2022-01-07 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INVOICES', '0008_auto_20220107_1825'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Osoby',
            new_name='Osoba',
        ),
    ]
