# Generated by Django 3.1.3 on 2022-01-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVOICES', '0009_auto_20220107_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='email',
            field=models.CharField(blank=True, max_length=200, verbose_name='Adres e-mail'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='skype',
            field=models.CharField(blank=True, max_length=200, verbose_name='Adres Skype'),
        ),
    ]
