# Generated by Django 3.1.3 on 2022-03-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVOICES', '0014_auto_20220130_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='faktura',
            name='dla_kogo',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Dla Kogo'),
        ),
        migrations.AlterField(
            model_name='faktura',
            name='confirm',
            field=models.CharField(choices=[('SKYPE', 'SKYPE'), ('E-MAIL', 'E-MAIL'), ('BEZ POTWIERDZENIA', 'BEZ POTWIERDZENIA')], default='BEZ POTWIERDZENIA', max_length=50, verbose_name='Potwierdzenie (smartinfo@smartdesign-expo.com)'),
        ),
    ]
