# Generated by Django 3.1.3 on 2022-11-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVOICES', '0016_auto_20220714_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktura',
            name='naz_imie',
            field=models.CharField(choices=[('', ''), ('Agnieszka Skóra', 'Agnieszka Skóra'), ('Julia Królak', 'Julia Królak'), ('Piotr Junik', 'Piotr Junik'), ('Dariusz Kaczmarek', 'Dariusz Kaczmarek'), ('Łukasz Jerzmanowski', 'Łukasz Jerzmanowski'), ('Michał Ogrzewalski', 'Michał Ogrzewalski'), ('Marzena Michalska', 'Marzena Michalska'), ('Łukasz Zaremba', 'Łukasz Zaremba'), ('Joanna Dittmar', 'Joanna Dittmar'), ('Bartosz Ługowski', 'Bartosz Ługowski'), ('Adam Beim', 'Adam Beim'), ('Eryk Przybyłowicz', 'Eryk Przybyłowicz'), ('Małgosia Świadek', 'Małgorzata Świadek'), ('Monika Stefańska', 'Monika Stefańska'), ('Katarzyna Rybak', 'Katarzyna Rybak'), ('Dariusz Grabowski', 'Dariusz Grabowski'), ('Jarosław Stróżyk', 'Jarosław Stróżyk')], default='', max_length=300, verbose_name='Imię i Nazwisko'),
        ),
    ]
