# Generated by Django 3.1.3 on 2023-01-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVOICES', '0022_auto_20230120_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='delega',
            field=models.BooleanField(default=False, verbose_name='Widoczny DEL'),
        ),
        migrations.AddField(
            model_name='osoba',
            name='invoice',
            field=models.BooleanField(default=False, verbose_name='Widoczny INV'),
        ),
    ]
