# Generated by Django 3.1.3 on 2023-01-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVOICES', '0023_auto_20230120_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='email',
            field=models.EmailField(error_messages={'required': 'Podaj swój adres e-mail.'}, max_length=254, verbose_name='Adres e-mail'),
        ),
    ]
