# Generated by Django 3.1.3 on 2023-01-21 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('INVOICES', '0024_auto_20230120_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='faktura',
            name='osoba',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='INVOICES.osoba', verbose_name='Imię i Nazwisko'),
        ),
    ]
