# Generated by Django 3.1.3 on 2025-01-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVOICES', '0037_alter_faktura_id_alter_osoba_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktura',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
