# Generated by Django 3.1.3 on 2020-11-28 10:33

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NrMPK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(blank=True, max_length=50, verbose_name='Nazwa')),
                ('opis', models.CharField(blank=True, max_length=500, verbose_name='Nazwa')),
                ('uwagi', models.TextField(blank=True, verbose_name='Uwagi')),
            ],
            options={
                'verbose_name': 'Numer MPK',
                'verbose_name_plural': 'Numery MPK',
            },
        ),
        migrations.CreateModel(
            name='NrSDE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(blank=True, max_length=250, verbose_name='Nazwa')),
                ('uwagi', models.TextField(blank=True, verbose_name='Uwagi')),
            ],
            options={
                'verbose_name': 'Numer SDE',
                'verbose_name_plural': 'Numery SDE',
            },
        ),
        migrations.CreateModel(
            name='Rozliczenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwisko', models.CharField(blank=True, max_length=250, verbose_name='Nazwisko i Imię')),
                ('uwagi', models.TextField(blank=True, verbose_name='Uwagi')),
            ],
            options={
                'verbose_name': 'Rozliczenie',
                'verbose_name_plural': 'Rozliczenia',
            },
        ),
        migrations.CreateModel(
            name='Pozycja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_fv', models.CharField(blank=True, max_length=100, verbose_name='Nr faktury')),
                ('opis', models.CharField(max_length=300, verbose_name='Opis zamówienia')),
                ('kontrahent', models.CharField(max_length=300, verbose_name='Kontrahent')),
                ('wartosc_zam_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar\xa0Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski Nowy')], default='PLN', editable=False, max_length=3)),
                ('wartosc_zam', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Wartość zamówienia')),
                ('nr_mpk', models.ForeignKey(blank=True, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='CASH_ADVANCES.rozliczenie', verbose_name='Rozliczenie')),
                ('nr_sde', models.ForeignKey(blank=True, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='CASH_ADVANCES.nrsde', verbose_name='Nr SDE')),
            ],
            options={
                'verbose_name': 'Pozycja',
                'verbose_name_plural': 'Pozycje',
            },
        ),
    ]
