# Generated by Django 3.1.3 on 2020-11-28 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CASH_ADVANCES', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozycja',
            name='nr_roz',
            field=models.ForeignKey(blank=True, default=1, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='CASH_ADVANCES.rozliczenie', verbose_name='Rozliczenie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pozycja',
            name='nr_mpk',
            field=models.ForeignKey(blank=True, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='CASH_ADVANCES.nrmpk', verbose_name='Nr MPK'),
        ),
    ]
