# Generated by Django 3.1.3 on 2020-11-28 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CASH_ADVANCES', '0002_auto_20201128_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pozycja',
            name='nr_mpk',
        ),
        migrations.RemoveField(
            model_name='pozycja',
            name='nr_roz',
        ),
        migrations.RemoveField(
            model_name='pozycja',
            name='nr_sde',
        ),
        migrations.DeleteModel(
            name='NrMPK',
        ),
        migrations.DeleteModel(
            name='NrSDE',
        ),
        migrations.DeleteModel(
            name='Pozycja',
        ),
        migrations.DeleteModel(
            name='Rozliczenie',
        ),
    ]
