# Generated by Django 3.1.3 on 2020-11-28 12:39

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CASH_ADVANCES', '0003_auto_20201128_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='NrMPK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(blank=True, max_length=50, verbose_name='Nazwa')),
                ('opis', models.CharField(blank=True, max_length=500, verbose_name='Nazwa')),
                ('uwagi', models.TextField(blank=True, verbose_name='Uwagi')),
            ],
            options={
                'verbose_name': 'Numer MPK',
                'verbose_name_plural': 'Numery MPK',
            },
        ),
        migrations.CreateModel(
            name='NrSDE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(blank=True, max_length=250, verbose_name='Nazwa')),
                ('uwagi', models.TextField(blank=True, verbose_name='Uwagi')),
            ],
            options={
                'verbose_name': 'Numer SDE',
                'verbose_name_plural': 'Numery SDE',
            },
        ),
        migrations.CreateModel(
            name='Rozliczenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_roz', models.DateField(default=django.utils.timezone.now, verbose_name='Data rozliczenia')),
                ('rok', models.IntegerField(default=0, verbose_name='Rok')),
                ('kw', models.CharField(max_length=300, verbose_name='Nr KW')),
                ('nazwisko', models.CharField(blank=True, max_length=250, verbose_name='Nazwisko i Imię')),
                ('zal1_data', models.DateField(default=django.utils.timezone.now, verbose_name='Data zaliczki 1')),
                ('zal1_kwota_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar\xa0Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski Nowy')], default='PLN', editable=False, max_length=3)),
                ('zal1_kwota', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Kwota zaliczki 1')),
                ('zal2_data', models.DateField(default=django.utils.timezone.now, verbose_name='Data zaliczki 2')),
                ('zal2_kwota_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar\xa0Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski Nowy')], default='PLN', editable=False, max_length=3)),
                ('zal2_kwota', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Kwota zaliczki 2')),
                ('zal3_data', models.DateField(default=django.utils.timezone.now, verbose_name='Data zaliczki 3')),
                ('zal3_kwota_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar\xa0Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski Nowy')], default='PLN', editable=False, max_length=3)),
                ('zal3_kwota', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Kwota zaliczki 3')),
                ('zal_suma_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar\xa0Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski Nowy')], default='PLN', editable=False, max_length=3)),
                ('zal_suma', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Suma zaliczek')),
                ('saldo_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar\xa0Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski Nowy')], default='PLN', editable=False, max_length=3)),
                ('saldo', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Saldo')),
                ('uwagi', models.TextField(blank=True, verbose_name='Uwagi')),
                ('kontrola', models.IntegerField(default=0, verbose_name='Kontrola')),
            ],
            options={
                'verbose_name': 'Rozliczenie',
                'verbose_name_plural': 'Rozliczenia',
            },
        ),
        migrations.CreateModel(
            name='Pozycja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok', models.IntegerField(default=0, verbose_name='Rok')),
                ('kontrahent', models.CharField(max_length=300, verbose_name='Kontrahent')),
                ('nr_fv', models.CharField(blank=True, max_length=100, verbose_name='Nr faktury')),
                ('kwota_netto_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar\xa0Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski Nowy')], default='PLN', editable=False, max_length=3)),
                ('kwota_netto', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Kwota netto')),
                ('kwota_brutto_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar\xa0Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski Nowy')], default='PLN', editable=False, max_length=3)),
                ('kwota_brutto', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Kwota brutto')),
                ('data_zak', models.DateField(default=django.utils.timezone.now, verbose_name='Data zakupu')),
                ('opis', models.CharField(max_length=300, verbose_name='Opis zamówienia')),
                ('kontrola', models.IntegerField(default=0, verbose_name='Kontrola')),
                ('nr_mpk', models.ForeignKey(blank=True, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='CASH_ADVANCES.nrmpk', verbose_name='Nr MPK')),
                ('nr_roz', models.ForeignKey(blank=True, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='CASH_ADVANCES.rozliczenie', verbose_name='Rozliczenie')),
                ('nr_sde', models.ForeignKey(blank=True, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='CASH_ADVANCES.nrsde', verbose_name='Nr SDE')),
            ],
            options={
                'verbose_name': 'Pozycja',
                'verbose_name_plural': 'Pozycje',
            },
        ),
    ]
