# Generated by Django 3.1.3 on 2020-11-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CASH_ADVANCES', '0004_nrmpk_nrsde_pozycja_rozliczenie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozycja',
            name='kontrola',
            field=models.IntegerField(blank=True, default=0, verbose_name='Kontrola'),
        ),
        migrations.AlterField(
            model_name='pozycja',
            name='opis',
            field=models.CharField(blank=True, max_length=300, verbose_name='Opis zamówienia'),
        ),
    ]
