# Generated by Django 3.1.3 on 2020-11-28 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CASH_ADVANCES', '0005_auto_20201128_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozycja',
            name='kontrahent',
            field=models.CharField(blank=True, max_length=300, verbose_name='Kontrahent'),
        ),
        migrations.AlterField(
            model_name='pozycja',
            name='nr_mpk',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='CASH_ADVANCES.nrmpk', verbose_name='Nr MPK'),
        ),
        migrations.AlterField(
            model_name='pozycja',
            name='nr_roz',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='CASH_ADVANCES.rozliczenie', verbose_name='Rozliczenie'),
        ),
        migrations.AlterField(
            model_name='pozycja',
            name='nr_sde',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='CASH_ADVANCES.nrsde', verbose_name='Nr SDE'),
        ),
    ]
