# Generated by Django 3.1.3 on 2020-12-01 19:44

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CASH_ADVANCES', '0009_auto_20201129_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rozliczenie',
            old_name='zal1_kwota_currency',
            new_name='zal_kwota_currency',
        ),
        migrations.RemoveField(
            model_name='rozliczenie',
            name='zal1_data',
        ),
        migrations.RemoveField(
            model_name='rozliczenie',
            name='zal1_kwota',
        ),
        migrations.RemoveField(
            model_name='rozliczenie',
            name='zal2_data',
        ),
        migrations.RemoveField(
            model_name='rozliczenie',
            name='zal2_kwota',
        ),
        migrations.RemoveField(
            model_name='rozliczenie',
            name='zal2_kwota_currency',
        ),
        migrations.RemoveField(
            model_name='rozliczenie',
            name='zal3_data',
        ),
        migrations.RemoveField(
            model_name='rozliczenie',
            name='zal3_kwota',
        ),
        migrations.RemoveField(
            model_name='rozliczenie',
            name='zal3_kwota_currency',
        ),
        migrations.AddField(
            model_name='pozycja',
            name='uwagi',
            field=models.TextField(blank=True, verbose_name='Uwagi'),
        ),
        migrations.AddField(
            model_name='rozliczenie',
            name='data_zal',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Data zaliczki'),
        ),
        migrations.AddField(
            model_name='rozliczenie',
            name='zal_kwota',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Kwota zaliczki'),
        ),
        migrations.AlterField(
            model_name='rozliczenie',
            name='zal_suma',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Suma wydatków'),
        ),
    ]
