# Generated by Django 3.1.3 on 2020-12-03 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CASH_ADVANCES', '0010_auto_20201201_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozycja',
            name='nr_roz',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='CASH_ADVANCES.rozliczenie', verbose_name='Zaliczka'),
        ),
    ]
