# Generated by Django 3.1.4 on 2020-12-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CASH_ADVANCES', '0012_auto_20201216_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrsde',
            name='opis',
            field=models.CharField(blank=True, max_length=500, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='nrmpk',
            name='opis',
            field=models.CharField(blank=True, max_length=500, verbose_name='Opis'),
        ),
    ]
