# Generated by Django 3.1.4 on 2020-12-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CASH_ADVANCES', '0013_auto_20201220_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrsde',
            name='targi',
            field=models.CharField(blank=True, max_length=500, verbose_name='Targi'),
        ),
    ]
