# Generated by Django 3.1.4 on 2021-01-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CASH_ADVANCES', '0015_auto_20201228_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozycja',
            name='inicjaly',
            field=models.CharField(blank=True, max_length=10, verbose_name='Inicjały'),
        ),
        migrations.AddField(
            model_name='rozliczenie',
            name='inicjaly',
            field=models.CharField(blank=True, max_length=10, verbose_name='Inicjały'),
        ),
    ]
