# Generated by Django 3.1.4 on 2021-01-02 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CASH_ADVANCES', '0016_auto_20210102_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozycja',
            name='nr_mpk',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CASH_ADVANCES.nrmpk', verbose_name='Nr MPK'),
        ),
        migrations.AlterField(
            model_name='pozycja',
            name='nr_sde',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CASH_ADVANCES.nrsde', verbose_name='Nr SDE'),
        ),
    ]
