# Generated by Django 3.1.4 on 2021-01-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CASH_ADVANCES', '0017_auto_20210102_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrmpk',
            name='rok',
            field=models.IntegerField(default=2021, verbose_name='Rok Nr MPK'),
        ),
        migrations.AddField(
            model_name='nrsde',
            name='rok',
            field=models.IntegerField(default=2021, verbose_name='Rok Nr SDE'),
        ),
    ]
