# Generated by Django 3.1.4 on 2021-01-02 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CASH_ADVANCES', '0018_auto_20210102_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rozliczenie',
            name='data_roz',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data rozliczenia'),
        ),
    ]
