# Generated by Django 3.1.5 on 2021-01-17 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CASH_ADVANCES', '0021_auto_20210116_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozycja',
            name='nr_roz',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='CASH_ADVANCES.rozliczenie', verbose_name='Zaliczka'),
        ),
    ]
