# Generated by Django 3.1.3 on 2021-02-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CASH_ADVANCES', '0022_auto_20210117_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rozliczenie',
            name='data_roz',
            field=models.DateField(blank=True, null=True, verbose_name='Data rozliczenia'),
        ),
    ]
