# Generated by Django 3.1.3 on 2021-02-23 07:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CASH_ADVANCES', '0023_auto_20210221_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozycja',
            name='data_zam',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data zamówienia'),
        ),
        migrations.AlterField(
            model_name='pozycja',
            name='data_zak',
            field=models.DateField(verbose_name='Data zakupu/FV'),
        ),
    ]
