# Generated by Django 3.1.3 on 2021-02-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CASH_ADVANCES', '0024_auto_20210223_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pozycja',
            name='data_zam',
        ),
        migrations.AlterField(
            model_name='pozycja',
            name='data_zak',
            field=models.DateField(blank=True, null=True, verbose_name='Data zakupu/Data FV'),
        ),
    ]
