# Generated by Django 3.1.3 on 2021-07-05 23:43

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CASH_ADVANCES', '0029_auto_20210223_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozycja',
            name='kurs_walut',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Kurs walut'),
        ),
        migrations.AddField(
            model_name='pozycja',
            name='kurs_walut_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='pozycja',
            name='kwota_netto_pl',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Kwota [NETTO PLN]'),
        ),
        migrations.AddField(
            model_name='pozycja',
            name='kwota_netto_pl_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
    ]
