# Generated by Django 3.1.3 on 2021-11-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CASH_ADVANCES', '0030_auto_20210705_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='rozliczenie',
            name='przek',
            field=models.BooleanField(default=False, verbose_name='Przekazano'),
        ),
    ]
