# Generated by Django 3.1.3 on 2021-11-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CASH_ADVANCES', '0031_rozliczenie_przek'),
    ]

    operations = [
        migrations.AddField(
            model_name='rozliczenie',
            name='flaga_zmian',
            field=models.BooleanField(default=False, verbose_name='Zmiany w pozycjach dla tej zaliczki'),
        ),
    ]
