# Generated by Django 3.1.3 on 2021-12-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CASH_ADVANCES', '0032_rozliczenie_flaga_zmian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rozliczenie',
            name='przek',
            field=models.BooleanField(default=False, verbose_name='Przekazano do rozliczenia'),
        ),
    ]
