# Generated by Django 5.0 on 2023-12-16 20:14

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CASH_ADVANCES', '0035_auto_20230402_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozycja',
            name='kurs_walut_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('DKK', 'DKK'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='pozycja',
            name='kwota_netto_pl_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('DKK', 'DKK'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
    ]
