# Generated by Django 3.1.3 on 2025-01-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CASH_ADVANCES', '0045_alter_pozycja_id_alter_rozliczenie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozycja',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rozliczenie',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
