# Generated by Django 3.1.3 on 2022-12-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adres IP')),
                ('nazwa', models.CharField(blank=True, max_length=250, verbose_name='Nazwa')),
                ('typ', models.CharField(blank=True, max_length=250, verbose_name='Typ')),
                ('opis', models.CharField(blank=True, max_length=250, verbose_name='Opis')),
                ('uwagi', models.TextField(blank=True, verbose_name='Uwagi')),
            ],
            options={
                'verbose_name': 'LAN',
                'verbose_name_plural': 'LAN-y',
            },
        ),
    ]
