# Generated by Django 5.0 on 2023-12-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAN_MAP', '0004_alter_lan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
