# Generated by Django 3.1.3 on 2023-12-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAN_MAP', '0005_alter_lan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
