# Generated by Django 3.1.3 on 2021-12-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToSaveLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('godz', models.TimeField(blank=True, null=True, verbose_name='Godz')),
                ('modul_id', models.IntegerField(default=0, verbose_name='ID Modułu')),
                ('komunikat_id', models.IntegerField(default=0, verbose_name='ID Komunikatu')),
                ('opis', models.CharField(max_length=100, verbose_name='Opis')),
            ],
            options={
                'verbose_name': 'ToSaveLog',
                'verbose_name_plural': 'ToSavelogs',
            },
        ),
    ]
