# Generated by Django 3.1.3 on 2021-12-16 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LOG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=150, verbose_name='Nazwa')),
            ],
            options={
                'verbose_name': 'Moduł',
                'verbose_name_plural': 'Moduły',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('godz', models.TimeField(blank=True, null=True, verbose_name='Godz')),
                ('opis', models.CharField(max_length=150, verbose_name='Opis')),
                ('komunikat_id', models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LOG.errorlist', verbose_name='ID Komunikatu')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, verbose_name='Nazwa')),
            ],
            options={
                'verbose_name': 'Moduł',
                'verbose_name_plural': 'Moduły',
            },
        ),
        migrations.DeleteModel(
            name='ToSaveLog',
        ),
        migrations.AddField(
            model_name='log',
            name='modul_id',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LOG.modul', verbose_name='ID Modułu'),
        ),
    ]
