# Generated by Django 3.1.3 on 2021-12-16 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOG', '0002_auto_20211216_2131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorlist',
            options={'verbose_name': 'ErrorList', 'verbose_name_plural': 'ErrorListy'},
        ),
    ]
