# Generated by Django 3.1.3 on 2021-12-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOG', '0003_auto_20211216_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlist',
            name='nazwa',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='modul',
            name='nazwa',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nazwa'),
        ),
    ]
