# Generated by Django 3.1.3 on 2021-12-16 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOG', '0004_auto_20211216_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='modul_id',
        ),
        migrations.DeleteModel(
            name='Modul',
        ),
    ]
