# Generated by Django 3.1.3 on 2021-12-16 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LOG', '0005_auto_20211216_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(blank=True, max_length=100, verbose_name='Nazwa')),
            ],
            options={
                'verbose_name': 'Moduł Źródłowy',
                'verbose_name_plural': 'Moduły Źródłowe',
            },
        ),
        migrations.AddField(
            model_name='log',
            name='modul_id',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LOG.modulname', verbose_name='ID Modułu'),
        ),
    ]
