# Generated by Django 3.1.3 on 2021-12-16 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOG', '0006_auto_20211216_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='komunikat_id',
            new_name='komunikat',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='modul_id',
            new_name='modul',
        ),
    ]
