# Generated by Django 3.1.3 on 2021-12-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOG', '0007_auto_20211216_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='kto',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Kto'),
        ),
        migrations.AlterField(
            model_name='log',
            name='opis',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Opis'),
        ),
    ]
