# Generated by Django 3.1.3 on 2021-12-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOG', '0009_auto_20211222_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlist',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='errorlist',
            name='status_id',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='Status id'),
        ),
    ]
