# Generated by Django 3.1.3 on 2021-12-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOG', '0010_auto_20211222_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagLoop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Log_id', models.DecimalField(decimal_places=0, default=0, max_digits=6, verbose_name='Status id')),
            ],
            options={
                'verbose_name': 'FlagLoop',
                'verbose_name_plural': 'FlagLoops',
            },
        ),
    ]
