# Generated by Django 3.1.3 on 2021-12-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOG', '0011_flagloop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flagloop',
            name='Log_id',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6, verbose_name='Flagi'),
        ),
    ]
