# Generated by Django 3.1.3 on 2021-12-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOG', '0012_auto_20211226_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='opis',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Opis'),
        ),
    ]
