# Generated by Django 3.1.3 on 2021-12-26 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOG', '0013_auto_20211226_1639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlagLoop',
        ),
    ]
