# Generated by Django 3.1.3 on 2022-01-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOG', '0014_delete_flagloop'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='nowy',
            field=models.BooleanField(default=False, verbose_name='Nowy wpis'),
        ),
    ]
