# Generated by Django 3.1.3 on 2023-05-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOG', '0015_log_nowy'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='czas',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='Czas'),
        ),
    ]
