# Generated by Django 3.1.3 on 2023-05-31 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LOG', '0016_log_czas'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='Status id')),
                ('status', models.CharField(blank=True, max_length=10, null=True, verbose_name='Status')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('godz', models.TimeField(blank=True, null=True, verbose_name='Godz')),
                ('opis', models.CharField(blank=True, max_length=400, null=True, verbose_name='Opis')),
                ('kto', models.CharField(blank=True, max_length=10, null=True, verbose_name='Kto')),
                ('czas', models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='Czas')),
                ('nowy', models.BooleanField(default=False, verbose_name='Nowy wpis')),
                ('komunikat', models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LOG.errorlist', verbose_name='ID Komunikatu')),
                ('modul', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LOG.modulname', verbose_name='ID Modułu')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
