# Generated by Django 3.1.3 on 2021-12-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SERVICES', '0002_usluga_data_waznosci'),
    ]

    operations = [
        migrations.AddField(
            model_name='usluga',
            name='termin',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='Termin'),
        ),
    ]
