# Generated by Django 3.1.3 on 2022-01-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SERVICES', '0004_usluga_okres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usluga',
            name='okres',
            field=models.CharField(choices=[('ROCZNY', 'ROCZNY.'), ('MIESIĘCZNY', 'MIESIECZNY.'), ('BEZPŁATNY', 'BEZPŁATNY.'), ('NIE DOTYCZY', 'NIE DOTYCZY.')], default='ROCZNY', max_length=20, verbose_name='Okres rozliczeniowy'),
        ),
    ]
