# Generated by Django 3.1.3 on 2022-10-07 14:57

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ORDERS', '0055_auto_20220714_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plyta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(blank=True, default='', max_length=100, verbose_name='Nazwa')),
                ('stan', models.IntegerField(default=0, verbose_name='Stan')),
                ('opis', models.TextField(blank=True, verbose_name='Opis')),
                ('cena_currency', djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3)),
                ('cena', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Cena')),
            ],
            options={
                'verbose_name': 'Plyta',
                'verbose_name_plural': 'Plyty',
            },
        ),
        migrations.CreateModel(
            name='Rozchod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('ilosc', models.IntegerField(default=0, verbose_name='Ilość')),
                ('kwota_currency', djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3)),
                ('kwota', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Cena')),
                ('nr_sde', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ORDERS.nrsde', verbose_name='Nr SDE')),
                ('plyta', models.ForeignKey(max_length=400, on_delete=django.db.models.deletion.CASCADE, to='TIMBER_WH.plyta', verbose_name='Płyta')),
            ],
            options={
                'verbose_name': 'Przychod',
                'verbose_name_plural': 'Przychody',
            },
        ),
        migrations.CreateModel(
            name='Przychod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('ilosc', models.IntegerField(default=0, verbose_name='Ilość')),
                ('cena_currency', djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3)),
                ('cena', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Cena')),
                ('plyta', models.ForeignKey(max_length=400, on_delete=django.db.models.deletion.CASCADE, to='TIMBER_WH.plyta', verbose_name='Płyta')),
            ],
            options={
                'verbose_name': 'Przychod',
                'verbose_name_plural': 'Przychody',
            },
        ),
    ]
