# Generated by Django 3.1.3 on 2022-10-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIMBER_WH', '0002_auto_20221008_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='rozchod',
            name='rokk',
            field=models.IntegerField(default=2022, verbose_name='Rok Nr SDE'),
        ),
    ]
