# Generated by Django 3.1.3 on 2022-10-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIMBER_WH', '0003_rozchod_rokk'),
    ]

    operations = [
        migrations.AddField(
            model_name='plyta',
            name='magazyn',
            field=models.CharField(choices=[('MAGAZYN1', 'MAGAZYN1.'), ('MAGAZYN2', 'MAGAZYN2.'), ('MAGAZYN3', 'MAGAZYN3.')], default='MAGAZYN1', max_length=50, verbose_name='Magazyn'),
        ),
    ]
