# Generated by Django 3.1.3 on 2022-10-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIMBER_WH', '0004_plyta_magazyn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plyta',
            name='magazyn',
            field=models.CharField(choices=[('MAGAZYN1', 'MAGAZYN Szparagowa'), ('MAGAZYN2', 'MAGAZYN Podolany'), ('MAGAZYN3', 'MAGAZYN3.')], default='MAGAZYN1', max_length=50, verbose_name='Magazyn'),
        ),
    ]
