# Generated by Django 3.1.3 on 2022-10-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIMBER_WH', '0005_auto_20221018_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='przychod',
            name='zrodlo',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Źródło przychodu'),
        ),
        migrations.AddField(
            model_name='rozchod',
            name='cel',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Cel rozchodu'),
        ),
    ]
