# Generated by Django 3.1.3 on 2022-10-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIMBER_WH', '0006_auto_20221023_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='przychod',
            name='zrodlo',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Źródło przychodu'),
        ),
        migrations.AlterField(
            model_name='rozchod',
            name='cel',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Cel rozchodu'),
        ),
    ]
