# Generated by Django 3.1.3 on 2022-10-23 23:00

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('TIMBER_WH', '0007_auto_20221023_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='przychod',
            name='cena_j',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Cena jednostkowa'),
        ),
        migrations.AddField(
            model_name='przychod',
            name='cena_j_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
    ]
