# Generated by Django 3.1.3 on 2022-12-15 16:41

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0059_auto_20221116_0610'),
        ('TIMBER_WH', '0008_auto_20221023_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zestawienie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rokk', models.IntegerField(default=2022, verbose_name='Rok Nr SDE')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('operacja', models.CharField(blank=True, default='', max_length=200, verbose_name='Operacja')),
                ('opis', models.CharField(blank=True, default='', max_length=200, verbose_name='Opis')),
                ('ilosc', models.IntegerField(default=0, verbose_name='Ilość')),
                ('kwota_currency', djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3)),
                ('kwota', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Kwota')),
                ('nr_sde', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ORDERS.nrsde', verbose_name='Nr SDE')),
                ('plyta', models.ForeignKey(max_length=400, on_delete=django.db.models.deletion.CASCADE, to='TIMBER_WH.plyta', verbose_name='Płyta')),
            ],
            options={
                'verbose_name': 'Zestawienie',
                'verbose_name_plural': 'Zestawienia',
            },
        ),
    ]
