# Generated by Django 3.1.3 on 2023-01-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIMBER_WH', '0009_zestawienie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rozchod',
            name='rokk',
            field=models.IntegerField(default=2023, verbose_name='Rok Nr SDE'),
        ),
        migrations.AlterField(
            model_name='zestawienie',
            name='rokk',
            field=models.IntegerField(default=2023, verbose_name='Rok Nr SDE'),
        ),
    ]
