# Generated by Django 3.1.3 on 2023-01-08 00:17

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0062_nrmpk_lsde'),
        ('TIMBER_WH', '0010_auto_20230101_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zwrot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rokk', models.IntegerField(default=2023, verbose_name='Rok Nr SDE')),
                ('cel', models.CharField(blank=True, default='', max_length=200, verbose_name='Opis zwrotu')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('ilosc', models.IntegerField(default=0, verbose_name='Ilość')),
                ('kwota_currency', djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3)),
                ('kwota', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Kwota')),
                ('nr_sde', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ORDERS.nrsde', verbose_name='Nr SDE')),
                ('plyta', models.ForeignKey(max_length=400, on_delete=django.db.models.deletion.CASCADE, to='TIMBER_WH.plyta', verbose_name='Płyta')),
            ],
            options={
                'verbose_name': 'Przychod',
                'verbose_name_plural': 'Przychody',
            },
        ),
    ]
