# Generated by Django 3.1.3 on 2023-01-08 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TIMBER_WH', '0011_zwrot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zwrot',
            options={'verbose_name': 'Zwrot', 'verbose_name_plural': 'Zwroty'},
        ),
    ]
