# Generated by Django 3.1.3 on 2023-01-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIMBER_WH', '0012_auto_20230108_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='plyta',
            name='rodzaj',
            field=models.CharField(choices=[('dre', 'MAGAZYN drewna'), ('wew', 'MAGAZYN wewnętrzny')], default='dre', max_length=50, verbose_name='Rodzaj Magazynu'),
        ),
    ]
