# Generated by Django 3.1.3 on 2023-01-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIMBER_WH', '0013_plyta_rodzaj'),
    ]

    operations = [
        migrations.AddField(
            model_name='przychod',
            name='jm',
            field=models.CharField(choices=[('m²', 'm²'), ('m³', 'm³'), ('mb', 'mb'), ('szt.', 'szt.'), ('kompl.', 'kompl.')], default='m²', max_length=50, verbose_name='Jednostka'),
        ),
        migrations.AddField(
            model_name='rozchod',
            name='jm',
            field=models.CharField(choices=[('m²', 'm²'), ('m³', 'm³'), ('mb', 'mb'), ('szt.', 'szt.'), ('kompl.', 'kompl.')], default='m²', max_length=50, verbose_name='Jednostka'),
        ),
    ]
