# Generated by Django 3.1.3 on 2023-01-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIMBER_WH', '0014_auto_20230114_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='plyta',
            name='jm',
            field=models.CharField(default='m²', max_length=50, verbose_name='Jednostka'),
        ),
    ]
