# Generated by Django 3.1.3 on 2023-01-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIMBER_WH', '0016_auto_20230115_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plyta',
            name='stan',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=11, verbose_name='Stan'),
        ),
        migrations.AlterField(
            model_name='przychod',
            name='ilosc',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=11, verbose_name='Ilość'),
        ),
        migrations.AlterField(
            model_name='rozchod',
            name='ilosc',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=11, verbose_name='Ilość'),
        ),
        migrations.AlterField(
            model_name='zestawienie',
            name='ilosc',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=11, verbose_name='Ilość'),
        ),
        migrations.AlterField(
            model_name='zwrot',
            name='ilosc',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=11, verbose_name='Ilość'),
        ),
    ]
