# Generated by Django 3.1.3 on 2023-01-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIMBER_WH', '0017_auto_20230115_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='zestawienie',
            name='dok_id',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Dok. ID'),
        ),
    ]
