# Generated by Django 3.1.3 on 2023-01-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIMBER_WH', '0018_zestawienie_dok_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='przychod',
            name='jm',
            field=models.CharField(choices=[('m²', 'm²'), ('m³', 'm³'), ('mb', 'mb'), ('szt.', 'szt.'), ('kompl.', 'kompl.')], default='szt.', max_length=50, verbose_name='Jednostka'),
        ),
    ]
