# Generated by Django 3.1.3 on 2023-01-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIMBER_WH', '0019_auto_20230116_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='plyta',
            name='prod_id',
            field=models.IntegerField(default=0, verbose_name='ID Prod.'),
        ),
    ]
