# Generated by Django 3.1.3 on 2023-01-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIMBER_WH', '0020_plyta_prod_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='przychod',
            name='doc_id',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='ID dok.'),
        ),
        migrations.AddField(
            model_name='rozchod',
            name='doc_id',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='ID dok.'),
        ),
        migrations.AddField(
            model_name='zwrot',
            name='doc_id',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='ID dok.'),
        ),
    ]
