# Generated by Django 3.1.3 on 2023-01-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIMBER_WH', '0021_auto_20230124_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plyta',
            name='jm',
            field=models.CharField(default='szt.', max_length=50, verbose_name='Jednostka'),
        ),
        migrations.AlterField(
            model_name='rozchod',
            name='jm',
            field=models.CharField(choices=[('m²', 'm²'), ('m³', 'm³'), ('mb', 'mb'), ('szt.', 'szt.'), ('kompl.', 'kompl.')], default='szt.', max_length=50, verbose_name='Jednostka'),
        ),
        migrations.AlterField(
            model_name='zwrot',
            name='jm',
            field=models.CharField(choices=[('m²', 'm²'), ('m³', 'm³'), ('mb', 'mb'), ('szt.', 'szt.'), ('kompl.', 'kompl.')], default='szt.', max_length=50, verbose_name='Jednostka'),
        ),
    ]
