# Generated by Django 3.1.3 on 2023-02-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIMBER_WH', '0022_auto_20230129_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='plyta',
            name='limit',
            field=models.DecimalField(decimal_places=1, default=10.0, max_digits=11, verbose_name='Limit'),
        ),
    ]
