# Generated by Django 3.1.3 on 2023-04-23 13:18

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0065_auto_20230402_2018'),
        ('TIMBER_WH', '0026_auto_20230421_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statystyka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rokk', models.IntegerField(default=2023, verbose_name='Rok')),
                ('mc', models.IntegerField(default=4, verbose_name='Miesiac')),
                ('kwota_currency', djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('DKK', 'DKK'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3)),
                ('kwota', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Kwota')),
                ('nr_sde', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ORDERS.nrsde', verbose_name='Nr SDE')),
            ],
            options={
                'verbose_name': 'Statystyka',
                'verbose_name_plural': 'Statystyki',
            },
        ),
    ]
