# Generated by Django 3.1.3 on 2023-04-23 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TIMBER_WH', '0027_statystyka'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statystyka',
        ),
    ]
