# Generated by Django 3.1.3 on 2023-05-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIMBER_WH', '0029_statystyka'),
    ]

    operations = [
        migrations.AddField(
            model_name='przychod',
            name='inwentura',
            field=models.BooleanField(default=False, verbose_name='Inwentura'),
        ),
        migrations.AddField(
            model_name='rozchod',
            name='inwentura',
            field=models.BooleanField(default=False, verbose_name='Inwentura'),
        ),
    ]
