# Generated by Django 3.1.3 on 2023-05-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIMBER_WH', '0032_auto_20230504_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='przychod',
            name='bo',
            field=models.BooleanField(default=False, verbose_name='Bilans otwarcia'),
        ),
        migrations.AddField(
            model_name='rozchod',
            name='bo',
            field=models.BooleanField(default=False, verbose_name='Bilans otwarcia'),
        ),
    ]
