# Generated by Django 3.1.3 on 2023-05-04 19:31

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('TIMBER_WH', '0033_auto_20230504_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='stanobecny',
            name='nadmiar',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=11, verbose_name='Nadmiar - Ilość'),
        ),
        migrations.AddField(
            model_name='stanobecny',
            name='p_cena_j',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Cena Jednostkowa'),
        ),
        migrations.AddField(
            model_name='stanobecny',
            name='p_cena_j_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('DKK', 'DKK'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='stanobecny',
            name='p_ilosc',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=11, verbose_name='Przychód - Ilość'),
        ),
        migrations.AddField(
            model_name='stanobecny',
            name='r_ilosc',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=11, verbose_name='Rozchód - Ilość'),
        ),
        migrations.AddField(
            model_name='stanobecny',
            name='stan',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=11, verbose_name='Stan - Ilość'),
        ),
        migrations.AddField(
            model_name='stanobecny',
            name='wartosc',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Wartość'),
        ),
        migrations.AddField(
            model_name='stanobecny',
            name='wartosc_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('DKK', 'DKK'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
    ]
