# Generated by Django 3.1.3 on 2023-05-04 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TIMBER_WH', '0034_auto_20230504_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stanobecny',
            options={'verbose_name': 'StanObecny', 'verbose_name_plural': 'StanyObecne'},
        ),
    ]
