# Generated by Django 3.1.3 on 2023-07-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIMBER_WH', '0035_auto_20230504_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inwentura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rokk', models.IntegerField(default=2023, verbose_name='Rok')),
            ],
            options={
                'verbose_name': 'Inwentura',
                'verbose_name_plural': 'Inwentury',
            },
        ),
    ]
