# Generated by Django 3.1.3 on 2023-07-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIMBER_WH', '0036_inwentura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plyta',
            name='magazyn',
            field=models.CharField(choices=[('MAGAZYN1', 'MAGAZYN Szparagowa'), ('MAGAZYN2', 'MAGAZYN Podolany'), ('MAGAZYN3', 'MAGAZYN Chemii'), ('MAGAZYN4', 'MAGAZYN Szkła')], default='MAGAZYN1', max_length=50, verbose_name='Magazyn'),
        ),
    ]
