# Generated by Django 3.1.3 on 2023-07-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIMBER_WH', '0037_auto_20230723_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='przychod',
            name='bo',
            field=models.BooleanField(default=False, verbose_name='Stan początkowy'),
        ),
    ]
