# Generated by Django 5.0 on 2024-01-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIMBER_WH', '0044_alter_inwentura_id_alter_plyta_id_alter_przychod_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwentura',
            name='rokk',
            field=models.IntegerField(default=2024, verbose_name='Rok'),
        ),
        migrations.AlterField(
            model_name='rozchod',
            name='rokk',
            field=models.IntegerField(default=2024, verbose_name='Rok Nr SDE'),
        ),
        migrations.AlterField(
            model_name='statystyka',
            name='rokk',
            field=models.IntegerField(default=2024, verbose_name='Rok'),
        ),
        migrations.AlterField(
            model_name='zestawienie',
            name='rokk',
            field=models.IntegerField(default=2024, verbose_name='Rok Nr SDE'),
        ),
        migrations.AlterField(
            model_name='zwrot',
            name='rokk',
            field=models.IntegerField(default=2024, verbose_name='Rok Nr SDE'),
        ),
    ]
