# Generated by Django 3.1.3 on 2024-01-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIMBER_WH', '0045_alter_inwentura_rokk_alter_rozchod_rokk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwentura',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='plyta',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='plyta',
            name='magazyn',
            field=models.CharField(choices=[('MAGAZYN1', 'MAGAZYN Szparagowa'), ('MAGAZYN2', 'MAGAZYN Podolany'), ('MAGAZYN3', 'MAGAZYN Chemii'), ('MAGAZYN4', 'MAGAZYN Szkła'), ('MAGAZYN5', 'MAGAZYN Stali')], default='MAGAZYN1', max_length=50, verbose_name='Magazyn'),
        ),
        migrations.AlterField(
            model_name='przychod',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rozchod',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stanobecny',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='statystyka',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='zestawienie',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='zwrot',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
