# Generated by Django 5.0 on 2024-12-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIMBER_WH', '0049_plyta_inw_data_plyta_inw_stan_alter_inwentura_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plyta',
            name='inw_data',
            field=models.DateField(blank=True, default='', verbose_name='Inwentura Data'),
        ),
    ]
