# Generated by Django 5.0 on 2024-12-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIMBER_WH', '0050_alter_plyta_inw_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plyta',
            name='inw_data',
            field=models.DateField(blank=True, null=True, verbose_name='Inwentura Data'),
        ),
    ]
