# Generated by Django 5.0 on 2025-01-03 20:42

import django.db.models.deletion
import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIMBER_WH', '0052_auto_20241230_0336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rozchod',
            options={'verbose_name': 'Rozchod', 'verbose_name_plural': 'Rozchod'},
        ),
        migrations.AlterField(
            model_name='inwentura',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inwentura',
            name='rokk',
            field=models.IntegerField(default=2025, verbose_name='Rok'),
        ),
        migrations.AlterField(
            model_name='plyta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='przychod',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rozchod',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rozchod',
            name='rokk',
            field=models.IntegerField(default=2025, verbose_name='Rok Nr SDE'),
        ),
        migrations.AlterField(
            model_name='stanobecny',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='statystyka',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='statystyka',
            name='rokk',
            field=models.IntegerField(default=2025, verbose_name='Rok'),
        ),
        migrations.AlterField(
            model_name='zestawienie',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='zestawienie',
            name='rokk',
            field=models.IntegerField(default=2025, verbose_name='Rok Nr SDE'),
        ),
        migrations.AlterField(
            model_name='zwrot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='zwrot',
            name='rokk',
            field=models.IntegerField(default=2025, verbose_name='Rok Nr SDE'),
        ),
        migrations.CreateModel(
            name='RozchodSzczegoly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.DecimalField(decimal_places=1, default=0.0, max_digits=11, verbose_name='Ilość')),
                ('cena_j_currency', djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('DKK', 'DKK'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3)),
                ('cena_j', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Cena jednostkowa')),
                ('kwota_currency', djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('DKK', 'DKK'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3)),
                ('kwota', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Kwota')),
                ('przychod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TIMBER_WH.przychod', verbose_name='Przychod')),
                ('rozchod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TIMBER_WH.rozchod', verbose_name='Rozchod')),
            ],
            options={
                'verbose_name': 'Szczegóły Rozchodu',
                'verbose_name_plural': 'Szczegóły Rozchodów',
            },
        ),
    ]
