# Generated by Django 2.2.3 on 2019-07-06 20:03

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirmaKasa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(choices=[('KO', 'Kasa ogólna'), ('KZ', 'Kasa zastrzeżona')], default='KO', max_length=100, verbose_name='Rodzaj kasy')),
                ('nazwa', models.CharField(blank=True, max_length=200, verbose_name='Nazwa firmy')),
                ('adres', models.CharField(blank=True, max_length=200, verbose_name='Ulica, numer')),
                ('miasto', models.CharField(blank=True, max_length=200, verbose_name='Kod pocztowy, Miasto')),
                ('nip', models.CharField(blank=True, max_length=200, verbose_name='NIP')),
                ('kasa', models.CharField(blank=True, max_length=200, verbose_name='Nazwa kasy')),
                ('konto', models.CharField(blank=True, max_length=200, verbose_name='Nr konta kasy')),
                ('bo_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar\xa0Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski Nowy')], default='PLN', editable=False, max_length=3)),
                ('bo', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Bilans otwarcia')),
                ('stan_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar\xa0Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski Nowy')], default='PLN', editable=False, max_length=3)),
                ('stan', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Stan')),
                ('data_bo', models.DateField(default=django.utils.timezone.now, verbose_name='Data bilansu')),
                ('uwagi', models.TextField(blank=True, verbose_name='Uwagi')),
            ],
            options={
                'verbose_name': 'FirmaKasa',
                'verbose_name_plural': 'FirmyKasy',
            },
        ),
        migrations.CreateModel(
            name='Waluta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab', models.CharField(blank=True, max_length=2, verbose_name='Typ tablicy')),
                ('kod', models.CharField(blank=True, max_length=5, verbose_name='Kod waluty')),
                ('poz', models.CharField(blank=True, max_length=50, verbose_name='Identyfikator tablicy')),
                ('data', models.CharField(blank=True, max_length=50, verbose_name='Data')),
                ('kurs', models.FloatField(blank=True, verbose_name='Kurs')),
                ('opis', models.CharField(blank=True, max_length=50, verbose_name='Opis')),
            ],
            options={
                'verbose_name': 'Waluta',
                'verbose_name_plural': 'Waluty',
            },
        ),
        migrations.CreateModel(
            name='RaportKasowy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('sum_przychod_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar\xa0Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski Nowy')], default='PLN', editable=False, max_length=3)),
                ('sum_przychod', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Sum przychód')),
                ('sum_rozchod_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar\xa0Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski Nowy')], default='PLN', editable=False, max_length=3)),
                ('sum_rozchod', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Sum rozchód')),
                ('stan_poprzedni_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar\xa0Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski Nowy')], default='PLN', editable=False, max_length=3)),
                ('stan_poprzedni', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Sum poprzedni')),
                ('stan_obecny_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar\xa0Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski Nowy')], default='PLN', editable=False, max_length=3)),
                ('stan_obecny', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Sum obecny')),
                ('kw', models.DecimalField(decimal_places=0, default=0, max_digits=11, verbose_name='KW')),
                ('kp', models.DecimalField(decimal_places=0, default=0, max_digits=11, verbose_name='KP')),
                ('mkw', models.DecimalField(decimal_places=0, default=0, max_digits=11, verbose_name='KW w m-c')),
                ('mkp', models.DecimalField(decimal_places=0, default=0, max_digits=11, verbose_name='KP w m-c')),
                ('kasa', models.ForeignKey(default=1, max_length=400, on_delete=django.db.models.deletion.CASCADE, to='RK.FirmaKasa', verbose_name='Firma&Kasa')),
            ],
            options={
                'verbose_name': 'RaportKasowy',
                'verbose_name_plural': 'RaportyKasowe',
            },
        ),
        migrations.CreateModel(
            name='KwKp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(choices=[('KW', 'KW'), ('KP', 'KP')], default='KW', max_length=100, verbose_name='Rodzaj')),
                ('numer', models.DecimalField(decimal_places=0, default=0, max_digits=11, verbose_name='Numer dokumentu')),
                ('nazwa', models.CharField(blank=True, max_length=200, verbose_name='Nazwa/Nazwisko i Imię')),
                ('adres', models.CharField(blank=True, max_length=200, verbose_name='Adres')),
                ('miasto', models.CharField(blank=True, max_length=200, verbose_name='Miasto i kod')),
                ('przychod_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar\xa0Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski Nowy')], default='PLN', editable=False, max_length=3)),
                ('przychod', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Przychód')),
                ('rozchod_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar\xa0Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski Nowy')], default='PLN', editable=False, max_length=3)),
                ('rozchod', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Rozchód')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('opis', models.CharField(blank=True, max_length=200, verbose_name='Opis')),
                ('uwagi', models.TextField(blank=True, verbose_name='Uwagi')),
                ('switch_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar\xa0Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski Nowy')], default='PLN', editable=False, max_length=3)),
                ('switch', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Wartość')),
                ('kasa', models.ForeignKey(max_length=400, on_delete=django.db.models.deletion.CASCADE, to='RK.FirmaKasa', verbose_name='Kasa')),
            ],
            options={
                'verbose_name': 'KwKp',
                'verbose_name_plural': 'KwKpy',
            },
        ),
    ]
