# Generated by Django 3.1.3 on 2020-11-28 23:55

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('RK', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmakasa',
            name='bo_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='firmakasa',
            name='stan_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='kwkp',
            name='przychod_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='kwkp',
            name='rozchod_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='kwkp',
            name='switch_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='raportkasowy',
            name='stan_obecny_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='raportkasowy',
            name='stan_poprzedni_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='raportkasowy',
            name='sum_przychod_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='raportkasowy',
            name='sum_rozchod_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski')], default='PLN', editable=False, max_length=3),
        ),
    ]
