# Generated by Django 2.2.3 on 2019-07-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=200, verbose_name='Data i Czas')),
                ('modul', models.CharField(max_length=200, verbose_name='Moduł')),
                ('usr', models.CharField(max_length=200, verbose_name='Użytkownik')),
                ('uwagi', models.CharField(max_length=200, verbose_name='Uwagi')),
            ],
            options={
                'verbose_name': 'System - Log',
                'verbose_name_plural': 'System - Logi',
            },
        ),
    ]
