# Generated by Django 2.2.3 on 2019-10-08 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cel', models.IntegerField(default=0, verbose_name='CEL')),
                ('adres', models.CharField(max_length=100, verbose_name='ADRES')),
                ('tytul', models.CharField(blank=True, max_length=100, verbose_name='TYTUŁ')),
                ('info', models.CharField(max_length=200, verbose_name='INFO')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='DATA WPROWADZENIA')),
            ],
            options={
                'verbose_name': 'Asp',
                'verbose_name_plural': 'Asp',
            },
        ),
        migrations.CreateModel(
            name='Waluta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab', models.CharField(max_length=2, verbose_name='TABELA')),
                ('kod', models.CharField(max_length=5, verbose_name='KOD')),
                ('poz', models.CharField(max_length=50, verbose_name='POZYCJA')),
                ('data', models.CharField(max_length=50, verbose_name='DATA')),
                ('opis', models.CharField(max_length=50, verbose_name='OPIS')),
                ('kurs', models.CharField(max_length=5, verbose_name='KURS')),
            ],
            options={
                'verbose_name': 'Waluta',
                'verbose_name_plural': 'Waluty',
            },
        ),
    ]
