# Generated by Django 2.2.3 on 2020-08-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAPI', '0003_auto_20200825_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asp',
            name='adres',
            field=models.CharField(max_length=200, verbose_name='ADRES'),
        ),
        migrations.AlterField(
            model_name='asp',
            name='tytul',
            field=models.CharField(blank=True, max_length=200, verbose_name='TYTUŁ'),
        ),
    ]
