# Generated by Django 2.2.3 on 2020-08-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAPI', '0004_auto_20200825_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asp',
            name='info',
            field=models.CharField(max_length=800, verbose_name='INFO'),
        ),
    ]
