# Generated by Django 3.1.3 on 2020-11-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAPI', '0006_flagazmiany'),
    ]

    operations = [
        migrations.AddField(
            model_name='flagazmiany',
            name='pozycja',
            field=models.BooleanField(default=False, verbose_name='Pozycja zmiana'),
        ),
    ]
