# Generated by Django 3.1.4 on 2020-12-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAPI', '0007_flagazmiany_pozycja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flagazmiany',
            name='pozycja',
            field=models.IntegerField(default=0, verbose_name='Zmiana Pozycja'),
        ),
        migrations.AlterField(
            model_name='flagazmiany',
            name='zamowienie',
            field=models.IntegerField(default=0, verbose_name='Zmiana Zamówienie'),
        ),
    ]
