# Generated by Django 3.1.4 on 2020-12-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAPI', '0008_auto_20201216_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='flagazmiany',
            name='rozliczenie',
            field=models.IntegerField(default=0, verbose_name='Zmiana Rozliczenia'),
        ),
    ]
