# Generated by Django 3.1.4 on 2021-01-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAPI', '0009_flagazmiany_rozliczenie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok', models.IntegerField(default=0, verbose_name='Rok')),
                ('flg', models.IntegerField(default=0, verbose_name='Flaga')),
            ],
            options={
                'verbose_name': 'Rok',
                'verbose_name_plural': 'Lata',
            },
        ),
        migrations.AlterModelOptions(
            name='flagazmiany',
            options={'verbose_name': 'Flaga', 'verbose_name_plural': 'Flagi'},
        ),
    ]
