# Generated by Django 3.1.3 on 2021-02-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAPI', '0010_auto_20210101_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='URok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200, verbose_name='Nazwa')),
                ('rok', models.IntegerField(default=0, verbose_name='Rok')),
            ],
            options={
                'verbose_name': 'URok',
                'verbose_name_plural': 'uLata',
            },
        ),
    ]
