# Generated by Django 3.1.3 on 2021-02-14 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAPI', '0011_urok'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urok',
            options={'verbose_name': 'URok', 'verbose_name_plural': 'ULata'},
        ),
    ]
