# Generated by Django 3.1.3 on 2021-04-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAPI', '0012_auto_20210214_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ustawienia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co', models.CharField(choices=[('Delegacja', 'Delegacja'), ('Faktury', 'Faktury'), ('Samochody', 'Samochody'), ('Ubezpieczenia', 'Ubezpieczenia')], default='Delegacja', max_length=100, verbose_name='Co')),
                ('medium', models.CharField(choices=[('EMAIL', 'EMAIL'), ('SKYPE', 'SKYPE')], default='EMAIL', max_length=100, verbose_name='Medium')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('skype', models.CharField(max_length=200, verbose_name='Skype')),
                ('dshift', models.IntegerField(default=0, verbose_name='Częstotliwość')),
                ('tshift', models.IntegerField(default=0, verbose_name='Uprzedzenie')),
            ],
            options={
                'verbose_name': 'Ustawienie',
                'verbose_name_plural': 'Ustawienia',
            },
        ),
    ]
