# Generated by Django 3.1.3 on 2021-05-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAPI', '0013_ustawienia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waluta',
            name='opis',
        ),
        migrations.RemoveField(
            model_name='waluta',
            name='poz',
        ),
    ]
