# Generated by Django 3.1.3 on 2021-05-23 16:50

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAPI', '0014_auto_20210523_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='waluta',
            name='kurs_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='waluta',
            name='kod',
            field=models.CharField(max_length=10, verbose_name='KOD'),
        ),
        migrations.AlterField(
            model_name='waluta',
            name='kurs',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='KURS'),
        ),
        migrations.AlterField(
            model_name='waluta',
            name='tab',
            field=models.CharField(max_length=50, verbose_name='TABELA'),
        ),
    ]
