# Generated by Django 3.1.3 on 2021-05-23 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAPI', '0015_auto_20210523_1650'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Waluta',
            new_name='WalutaNBP',
        ),
    ]
