# Generated by Django 3.1.3 on 2021-07-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAPI', '0017_auto_20210523_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='flagazmiany',
            name='licznik',
            field=models.IntegerField(default=0, verbose_name='Licznik'),
        ),
    ]
