# Generated by Django 3.1.3 on 2021-10-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAPI', '0018_flagazmiany_licznik'),
    ]

    operations = [
        migrations.AddField(
            model_name='flagazmiany',
            name='do_google',
            field=models.IntegerField(default=0, verbose_name='Wyjście do Google'),
        ),
    ]
