# Generated by Django 3.1.3 on 2021-12-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAPI', '0019_flagazmiany_do_google'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asp',
            name='info',
            field=models.CharField(max_length=5000, verbose_name='INFO'),
        ),
    ]
