# Generated by Django 3.1.3 on 2021-12-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAPI', '0020_auto_20211219_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='flagazmiany',
            name='loop_count',
            field=models.IntegerField(default=0, verbose_name='Licznik loop'),
        ),
    ]
