# Generated by Django 3.1.3 on 2023-06-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAPI', '0022_auto_20230402_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asp',
            name='info',
            field=models.CharField(max_length=10000, verbose_name='INFO'),
        ),
    ]
