# Generated by Django 3.1.3 on 2023-06-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAPI', '0023_auto_20230610_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asp',
            name='info',
            field=models.CharField(max_length=12000, verbose_name='INFO'),
        ),
    ]
