# Generated by Django 5.0 on 2023-12-16 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAPI', '0027_alter_asp_id_alter_flagazmiany_id_alter_log_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
