# Generated by Django 5.0 on 2024-07-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAPI', '0035_katalog_alter_asp_id_alter_flagazmiany_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalog',
            name='opis',
            field=models.CharField(blank=True, max_length=200, verbose_name='Opis'),
        ),
    ]
