# Generated by Django 5.0 on 2024-07-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAPI', '0036_alter_katalog_opis'),
    ]

    operations = [
        migrations.AddField(
            model_name='plik',
            name='form',
            field=models.BooleanField(default=False, verbose_name='Formularz'),
        ),
    ]
