# Generated by Django 3.1.3 on 2022-01-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pracownik',
            name='dzial',
            field=models.CharField(blank=True, choices=[], default='', max_length=300, verbose_name='Dział'),
        ),
    ]
