# Generated by Django 3.1.3 on 2022-01-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0004_auto_20220112_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pracownik',
            name='grupa',
            field=models.CharField(choices=[('BIURO', 'BIURO'), ('PRODUKCJA', 'PRODUKCJA')], default='', max_length=300, verbose_name='Grupa'),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='zatrudnienie',
            field=models.CharField(blank=True, choices=[('UMOWA', 'UMOWA'), ('DZIAŁALNOŚĆ', 'DZIAŁALNOŚĆ')], default='UMOWA', max_length=300, verbose_name='Zatrudnienie'),
        ),
    ]
