# Generated by Django 3.1.3 on 2022-01-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0005_auto_20220112_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pracownik',
            name='data_zat',
            field=models.DateField(verbose_name='Data zatrudnienia'),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='grupa',
            field=models.CharField(blank=True, choices=[('BIURO', 'BIURO'), ('PRODUKCJA', 'PRODUKCJA')], default='', max_length=300, verbose_name='Grupa'),
        ),
    ]
