# Generated by Django 3.1.3 on 2022-01-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0006_auto_20220112_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pracownik',
            name='data_zat',
            field=models.DateField(blank=True, null=True, verbose_name='Data zatrudnienia'),
        ),
    ]
