# Generated by Django 3.1.3 on 2022-01-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0009_auto_20220112_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensja',
            name='miesiac',
            field=models.IntegerField(default=1, verbose_name='Miesiąc'),
        ),
        migrations.AddField(
            model_name='pensja',
            name='rok',
            field=models.IntegerField(default=2022, verbose_name='Rok'),
        ),
    ]
