# Generated by Django 3.1.3 on 2022-01-30 17:18

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0010_auto_20220112_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='pracownik',
            name='ppk',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='PPK'),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='ppk_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
    ]
