# Generated by Django 3.1.3 on 2022-02-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0013_auto_20220203_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensja',
            name='del_ilosc_opis',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Opis delegacji'),
        ),
    ]
