# Generated by Django 3.1.3 on 2022-02-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0014_pensja_del_ilosc_opis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pracownik',
            name='dzial',
            field=models.CharField(blank=True, choices=[('PROJEKTANT', 'PROJEKTANT'), ('GRAFIK', 'GRAFIK'), ('MARKETING', 'MARKETING'), ('TM', 'TM'), ('PM', 'PM'), ('LOGISTYKA', 'LOGISTYKA'), ('KIEROWCA', 'KIEROWCA'), ('CNC', 'CNC'), ('STOLARZ', 'STOLARZ'), ('MONTAZYSTA', 'MONTAZYSTA'), ('MAGAZYN', 'MAGAZYN'), ('ZAOPATRZENIE', 'ZAOPATRZENIE'), ('ADMINISTRACJA', 'ADMINISTRACJA'), ('ZARZĄD', 'ZARZĄD')], default='', max_length=300, verbose_name='Dział'),
        ),
    ]
