# Generated by Django 3.1.3 on 2022-02-04 18:37

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0015_auto_20220204_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensja',
            name='przelew',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, null=True, verbose_name='Przelew'),
        ),
    ]
