# Generated by Django 3.1.3 on 2022-02-06 12:12

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0017_auto_20220206_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensja',
            name='przelew',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Przelew'),
        ),
        migrations.AlterField(
            model_name='pensja',
            name='wyplata',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Wypłata'),
        ),
    ]
