# Generated by Django 3.1.3 on 2022-02-06 14:37

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0019_pensja_km_dystans'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensja',
            name='stawka_nadgodz',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Nadgodziny stawka'),
        ),
        migrations.AddField(
            model_name='pensja',
            name='stawka_nadgodz_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='pensja',
            name='stawka_wyj',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Wyjazd stawka'),
        ),
        migrations.AddField(
            model_name='pensja',
            name='stawka_wyj_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='pracuje',
            field=models.BooleanField(default=True, verbose_name='Pracuje'),
        ),
    ]
