# Generated by Django 3.1.3 on 2022-02-06 15:32

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0020_auto_20220206_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensja',
            name='km_stawka',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Kilome. stawka'),
        ),
        migrations.AddField(
            model_name='pensja',
            name='km_stawka_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
    ]
