# Generated by Django 3.1.3 on 2022-02-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0021_auto_20220206_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_load', models.FileField(blank=True, upload_to='import', verbose_name='Pliki PDF')),
            ],
        ),
    ]
