# Generated by Django 3.1.3 on 2022-02-16 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0022_import'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='import',
            options={'verbose_name': 'Import', 'verbose_name_plural': 'Importy'},
        ),
    ]
