# Generated by Django 3.1.3 on 2022-03-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0023_auto_20220216_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensja',
            name='osoba',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Imię i Nazwisko'),
        ),
        migrations.AlterField(
            model_name='pensja',
            name='dodatek_opis',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Extra dodatek - opis'),
        ),
        migrations.AlterField(
            model_name='pensja',
            name='miesiac',
            field=models.IntegerField(default=3, verbose_name='Miesiąc'),
        ),
    ]
