# Generated by Django 3.1.3 on 2022-03-06 15:19

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0024_auto_20220304_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podsumowanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok', models.IntegerField(default=2022, verbose_name='Rok')),
                ('miesiac', models.IntegerField(default=3, verbose_name='Miesiąc')),
                ('suma_biuro_currency', djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3)),
                ('suma_biuro', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Suma biuro')),
            ],
            options={
                'verbose_name': 'Podsumowanie',
                'verbose_name_plural': 'Podsumowania',
            },
        ),
    ]
