# Generated by Django 3.1.3 on 2022-03-29 18:37

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0025_podsumowanie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stoisko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wielkosc', models.CharField(blank=True, default='', max_length=200, verbose_name='Wielkość stoiska')),
                ('premia_currency', djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3)),
                ('premia', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Premia')),
            ],
            options={
                'verbose_name': 'Stoisko',
                'verbose_name_plural': 'Stoiska',
            },
        ),
        migrations.RemoveField(
            model_name='pensja',
            name='del_ilosc_100',
        ),
        migrations.RemoveField(
            model_name='pensja',
            name='del_ilosc_50',
        ),
        migrations.AddField(
            model_name='pensja',
            name='del_ilosc_st',
            field=models.IntegerField(default=0, verbose_name='Wyjazd standard'),
        ),
        migrations.AddField(
            model_name='pensja',
            name='del_ilosc_we',
            field=models.IntegerField(default=0, verbose_name='Wyjazd weekend'),
        ),
    ]
