# Generated by Django 3.1.3 on 2022-03-29 21:49

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0050_auto_20220107_1646'),
        ('WORKER', '0026_auto_20220329_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok', models.IntegerField(default=2022, verbose_name='Rok')),
                ('miesiac', models.IntegerField(default=3, verbose_name='Miesiąc')),
                ('del_ilosc_st', models.IntegerField(default=0, verbose_name='Wyjazd standard')),
                ('del_ilosc_we', models.IntegerField(default=0, verbose_name='Wyjazd weekend')),
                ('del_ilosc_razem_currency', djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3)),
                ('del_ilosc_razem', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Wyjazd razem')),
                ('kw_sprzedazy_currency', djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3)),
                ('kw_sprzedazy', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Kwota sprzedaży')),
                ('premia_proj_currency', djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3)),
                ('premia_proj', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Premia za projekt')),
                ('ind_pr_nazwa', models.CharField(blank=True, default='', max_length=200, verbose_name='Nazwa projektu')),
                ('ind_pr_kwota_currency', djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3)),
                ('ind_pr_kwota', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Premia za projekt')),
                ('pracownik', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WORKER.pracownik', verbose_name='Pracownik')),
                ('projekt', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ORDERS.nrsde', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'Premia',
                'verbose_name_plural': 'Premie',
            },
        ),
    ]
