# Generated by Django 3.1.3 on 2022-03-29 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0027_premia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stoisko',
            old_name='premia',
            new_name='w_premii',
        ),
        migrations.RenameField(
            model_name='stoisko',
            old_name='premia_currency',
            new_name='w_premii_currency',
        ),
        migrations.AddField(
            model_name='premia',
            name='pr_wielkosc',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WORKER.stoisko', verbose_name='Wielkość stoiska'),
        ),
    ]
