# Generated by Django 3.1.3 on 2022-04-04 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0029_auto_20220403_2355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Premia',
        ),
    ]
