# Generated by Django 3.1.3 on 2022-04-04 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0051_auto_20220330_1909'),
        ('WORKER', '0030_delete_premia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premia_det',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pensja', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WORKER.pensja', verbose_name='Pensja')),
                ('projekt', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ORDERS.nrsde', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'Premia',
                'verbose_name_plural': 'Premie',
            },
        ),
    ]
