# Generated by Django 3.1.3 on 2022-04-04 00:28

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0031_premia_det'),
    ]

    operations = [
        migrations.AddField(
            model_name='premia_det',
            name='del_ilosc_razem',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Wyjazd razem'),
        ),
        migrations.AddField(
            model_name='premia_det',
            name='del_ilosc_razem_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='premia_det',
            name='del_ilosc_st',
            field=models.IntegerField(default=0, verbose_name='Wyjazd standard'),
        ),
        migrations.AddField(
            model_name='premia_det',
            name='del_ilosc_we',
            field=models.IntegerField(default=0, verbose_name='Wyjazd weekend'),
        ),
        migrations.AddField(
            model_name='premia_det',
            name='ind_pr_kwota',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Indywid. premia za projekt'),
        ),
        migrations.AddField(
            model_name='premia_det',
            name='ind_pr_kwota_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='premia_det',
            name='kw_sprzedazy',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Kwota sprzedaży'),
        ),
        migrations.AddField(
            model_name='premia_det',
            name='kw_sprzedazy_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='premia_det',
            name='pr_wartosc',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Premia za stoisko'),
        ),
        migrations.AddField(
            model_name='premia_det',
            name='pr_wartosc_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='premia_det',
            name='pr_wielkosc',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WORKER.stoisko', verbose_name='Wielkość stoiska'),
        ),
        migrations.AddField(
            model_name='premia_det',
            name='premia_proj',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Premia za projekt'),
        ),
        migrations.AddField(
            model_name='premia_det',
            name='premia_proj_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
    ]
