# Generated by Django 3.1.3 on 2022-04-04 01:44

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0051_auto_20220330_1909'),
        ('WORKER', '0032_auto_20220404_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premia_det',
            name='del_ilosc_st',
            field=models.IntegerField(default=0, verbose_name='Ilośc dni roboczych'),
        ),
        migrations.AlterField(
            model_name='premia_det',
            name='del_ilosc_we',
            field=models.IntegerField(default=0, verbose_name='Ilość dni weekendowych'),
        ),
        migrations.AlterField(
            model_name='premia_det',
            name='ind_pr_kwota',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Indywidualna premia'),
        ),
        migrations.AlterField(
            model_name='premia_det',
            name='projekt',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ORDERS.nrsde', verbose_name='Projekt'),
        ),
    ]
