# Generated by Django 3.1.3 on 2022-04-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0033_auto_20220404_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensja',
            name='premia_opis',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Opis premii'),
        ),
    ]
