# Generated by Django 3.1.3 on 2022-05-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0034_pensja_premia_opis'),
    ]

    operations = [
        migrations.AddField(
            model_name='premia_det',
            name='akc',
            field=models.BooleanField(default=False, verbose_name='Akceptacja'),
        ),
        migrations.AlterField(
            model_name='pensja',
            name='miesiac',
            field=models.IntegerField(default=5, verbose_name='Miesiąc'),
        ),
        migrations.AlterField(
            model_name='podsumowanie',
            name='miesiac',
            field=models.IntegerField(default=5, verbose_name='Miesiąc'),
        ),
    ]
