# Generated by Django 3.1.3 on 2022-05-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0035_auto_20220502_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='premia_det',
            name='ind_pr_opis',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Opis premii'),
        ),
    ]
