# Generated by Django 3.1.3 on 2022-06-06 00:56

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0036_premia_det_ind_pr_opis'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensja',
            name='suma_pd',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Suma premii i delegacji'),
        ),
        migrations.AddField(
            model_name='pensja',
            name='suma_pd_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='pensja',
            name='miesiac',
            field=models.IntegerField(default=6, verbose_name='Miesiąc'),
        ),
        migrations.AlterField(
            model_name='podsumowanie',
            name='miesiac',
            field=models.IntegerField(default=6, verbose_name='Miesiąc'),
        ),
    ]
