# Generated by Django 3.1.3 on 2022-07-14 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0054_auto_20220614_0552'),
        ('WORKER', '0037_auto_20220606_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='premia_det',
            name='pr_mpk',
            field=models.BooleanField(default=False, verbose_name='MPK [kod: 464]'),
        ),
        migrations.AlterField(
            model_name='pensja',
            name='miesiac',
            field=models.IntegerField(default=7, verbose_name='Miesiąc'),
        ),
        migrations.AlterField(
            model_name='podsumowanie',
            name='miesiac',
            field=models.IntegerField(default=7, verbose_name='Miesiąc'),
        ),
        migrations.AlterField(
            model_name='premia_det',
            name='projekt',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ORDERS.nrsde', verbose_name='Projekt'),
        ),
    ]
