# Generated by Django 3.1.3 on 2022-07-14 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0038_auto_20220714_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premia_det',
            name='pr_mpk',
        ),
    ]
