# Generated by Django 3.1.3 on 2022-09-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0040_auto_20220803_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensja',
            name='miesiac',
            field=models.IntegerField(default=9, verbose_name='Miesiąc'),
        ),
        migrations.AlterField(
            model_name='podsumowanie',
            name='miesiac',
            field=models.IntegerField(default=9, verbose_name='Miesiąc'),
        ),
    ]
