# Generated by Django 3.1.3 on 2022-10-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0041_auto_20220901_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensja',
            name='miesiac',
            field=models.IntegerField(default=10, verbose_name='Miesiąc'),
        ),
        migrations.AlterField(
            model_name='podsumowanie',
            name='miesiac',
            field=models.IntegerField(default=10, verbose_name='Miesiąc'),
        ),
    ]
