# Generated by Django 3.1.3 on 2022-10-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0042_auto_20221003_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='premia_det',
            name='del_ilosc_so',
            field=models.IntegerField(default=0, verbose_name='Ilość dni weekendowych [SO]'),
        ),
        migrations.AlterField(
            model_name='premia_det',
            name='del_ilosc_we',
            field=models.IntegerField(default=0, verbose_name='Ilość dni weekendowych [ND]'),
        ),
    ]
