# Generated by Django 3.1.3 on 2022-10-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0043_auto_20221008_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensja',
            name='del_ilosc_so',
            field=models.IntegerField(default=0, verbose_name='Wyjazd weekend [SO]'),
        ),
        migrations.AlterField(
            model_name='pensja',
            name='del_ilosc_we',
            field=models.IntegerField(default=0, verbose_name='Wyjazd weekend [ND]'),
        ),
    ]
