# Generated by Django 3.1.3 on 2022-11-07 19:28

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0045_auto_20221103_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensja',
            name='del_rozli',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Różnica rozliczenie'),
        ),
        migrations.AddField(
            model_name='pensja',
            name='del_rozli_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
    ]
