# Generated by Django 3.1.3 on 2022-11-09 10:48

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0046_auto_20221107_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='pracownik',
            name='stawka_wyj_rob',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Wyjazd stawka dni rob.'),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='stawka_wyj_rob_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
    ]
