# Generated by Django 3.1.3 on 2023-01-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0049_auto_20221215_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensja',
            name='miesiac',
            field=models.IntegerField(default=1, verbose_name='Miesiąc'),
        ),
        migrations.AlterField(
            model_name='pensja',
            name='rok',
            field=models.IntegerField(default=2023, verbose_name='Rok'),
        ),
        migrations.AlterField(
            model_name='podsumowanie',
            name='miesiac',
            field=models.IntegerField(default=1, verbose_name='Miesiąc'),
        ),
        migrations.AlterField(
            model_name='podsumowanie',
            name='rok',
            field=models.IntegerField(default=2023, verbose_name='Rok'),
        ),
    ]
