# Generated by Django 3.1.3 on 2023-02-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0050_auto_20230101_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensja',
            name='miesiac',
            field=models.IntegerField(default=2, verbose_name='Miesiąc'),
        ),
        migrations.AlterField(
            model_name='podsumowanie',
            name='miesiac',
            field=models.IntegerField(default=2, verbose_name='Miesiąc'),
        ),
    ]
