# Generated by Django 3.1.3 on 2023-03-19 15:11

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0051_auto_20230201_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensja',
            name='miesiac',
            field=models.IntegerField(default=3, verbose_name='Miesiąc'),
        ),
        migrations.AlterField(
            model_name='pensja',
            name='obciazenie',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Obciążenie'),
        ),
        migrations.AlterField(
            model_name='pensja',
            name='obciazenie_opis',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Opis obciążenia'),
        ),
        migrations.AlterField(
            model_name='podsumowanie',
            name='miesiac',
            field=models.IntegerField(default=3, verbose_name='Miesiąc'),
        ),
    ]
