# Generated by Django 3.1.3 on 2023-05-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0053_auto_20230402_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='pracownik',
            name='maska',
            field=models.BooleanField(default=False, verbose_name='Maska - nie wyświetlać'),
        ),
        migrations.AlterField(
            model_name='pensja',
            name='miesiac',
            field=models.IntegerField(default=5, verbose_name='Miesiąc'),
        ),
        migrations.AlterField(
            model_name='podsumowanie',
            name='miesiac',
            field=models.IntegerField(default=5, verbose_name='Miesiąc'),
        ),
    ]
