# Generated by Django 3.1.3 on 2023-05-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0054_auto_20230502_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensja',
            name='blokada',
            field=models.BooleanField(default=False, verbose_name='Blokada miesiąca'),
        ),
    ]
