# Generated by Django 3.1.3 on 2023-08-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0057_auto_20230712_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensja',
            name='miesiac',
            field=models.IntegerField(default=8, verbose_name='Miesiąc'),
        ),
        migrations.AlterField(
            model_name='podsumowanie',
            name='miesiac',
            field=models.IntegerField(default=8, verbose_name='Miesiąc'),
        ),
    ]
