# Generated by Django 3.1.3 on 2023-10-10 14:58

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0059_auto_20230917_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='pracownik',
            name='pensja_brutto',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Pensja [brutto]'),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='pensja_brutto_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('DKK', 'DKK'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='stawka_godz',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Stawka godz.'),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='stawka_godz_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('DKK', 'DKK'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='pensja',
            name='miesiac',
            field=models.IntegerField(default=10, verbose_name='Miesiąc'),
        ),
        migrations.AlterField(
            model_name='podsumowanie',
            name='miesiac',
            field=models.IntegerField(default=10, verbose_name='Miesiąc'),
        ),
    ]
