# Generated by Django 3.1.3 on 2023-10-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0060_auto_20231010_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='pracownik',
            name='lp_biuro',
            field=models.BooleanField(default=True, verbose_name='Lista płac biura'),
        ),
    ]
