# Generated by Django 3.1.3 on 2023-12-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0061_pracownik_lp_biuro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensja',
            name='miesiac',
            field=models.IntegerField(default=12, verbose_name='Miesiąc'),
        ),
        migrations.AlterField(
            model_name='podsumowanie',
            name='miesiac',
            field=models.IntegerField(default=12, verbose_name='Miesiąc'),
        ),
    ]
