# Generated by Django 5.0 on 2023-12-24 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0068_alter_import_id_alter_pensja_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pracownik',
            name='dystans',
        ),
        migrations.RemoveField(
            model_name='pracownik',
            name='ppk',
        ),
        migrations.RemoveField(
            model_name='pracownik',
            name='ppk_currency',
        ),
        migrations.RemoveField(
            model_name='pracownik',
            name='stawka_nadgodz',
        ),
        migrations.RemoveField(
            model_name='pracownik',
            name='stawka_nadgodz_currency',
        ),
    ]
