# Generated by Django 5.0 on 2023-12-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0069_remove_pracownik_dystans_remove_pracownik_ppk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pracownik',
            name='dystans',
            field=models.IntegerField(default=0, verbose_name='Dystans [km]'),
        ),
    ]
