# Generated by Django 5.0 on 2023-12-24 11:16

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0070_pracownik_dystans'),
    ]

    operations = [
        migrations.AddField(
            model_name='pracownik',
            name='ppk',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='PPK'),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='ppk_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('DKK', 'DKK'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
    ]
