# Generated by Django 3.1.3 on 2024-04-17 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0074_auto_20240306_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensja',
            name='miesiac',
            field=models.IntegerField(default=4, verbose_name='Miesiąc'),
        ),
        migrations.AlterField(
            model_name='podsumowanie',
            name='miesiac',
            field=models.IntegerField(default=4, verbose_name='Miesiąc'),
        ),
    ]
