# Generated by Django 3.1.3 on 2024-07-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0077_auto_20240421_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensja',
            name='miesiac',
            field=models.IntegerField(default=7, verbose_name='Miesiąc'),
        ),
        migrations.AlterField(
            model_name='podsumowanie',
            name='miesiac',
            field=models.IntegerField(default=7, verbose_name='Miesiąc'),
        ),
    ]
