# Generated by Django 3.1.3 on 2024-09-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0078_auto_20240708_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensja',
            name='miesiac',
            field=models.IntegerField(default=9, verbose_name='Miesiąc'),
        ),
        migrations.AlterField(
            model_name='podsumowanie',
            name='miesiac',
            field=models.IntegerField(default=9, verbose_name='Miesiąc'),
        ),
    ]
