# Generated by Django 3.1.3 on 2024-12-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0081_auto_20241117_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensja',
            name='miesiac',
            field=models.IntegerField(default=12, verbose_name='Miesiąc'),
        ),
        migrations.AlterField(
            model_name='podsumowanie',
            name='miesiac',
            field=models.IntegerField(default=12, verbose_name='Miesiąc'),
        ),
    ]
