# Generated by Django 3.1.3 on 2025-04-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0085_auto_20250213_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensja',
            name='miesiac',
            field=models.IntegerField(default=4, verbose_name='Miesiąc'),
        ),
        migrations.AlterField(
            model_name='podsumowanie',
            name='miesiac',
            field=models.IntegerField(default=4, verbose_name='Miesiąc'),
        ),
    ]
