# Generated by Django 3.1.3 on 2025-06-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKER', '0087_auto_20250511_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensja',
            name='miesiac',
            field=models.IntegerField(default=6, verbose_name='Miesiąc'),
        ),
        migrations.AlterField(
            model_name='podsumowanie',
            name='miesiac',
            field=models.IntegerField(default=6, verbose_name='Miesiąc'),
        ),
    ]
