# Generated by Django 3.1.3 on 2025-03-29 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO_NEW', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RejestrOperacji',
        ),
        migrations.DeleteModel(
            name='UprawnieniaPracownika',
        ),
        migrations.AlterField(
            model_name='sklad',
            name='okres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='COMP_REPO_NEW.okresprzechowywania', verbose_name='Okres przechowywania'),
        ),
    ]
