# Generated by Django 3.1.3 on 2025-03-29 19:35

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO_NEW', '0002_auto_20250329_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sklad',
            name='czas_do',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='czas_od',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='do_skasowania',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='faktura',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='ilosc_dni',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='liczyc',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='multi_uzycie',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='multi_uzycie_id',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='multi_uzycie_st',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='przech_gl',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='przech_pow',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='przech_sze',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='przech_wys',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='przech_zdjecie',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='przech_zdjecie2',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='przech_zdjecie3',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='przech_zdjecie4',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='uszkodz_zdjecie1',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='uszkodz_zdjecie2',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='uszkodz_zdjecie3',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='uszkodz_zdjecie4',
        ),
        migrations.AddField(
            model_name='elementkatalogowy',
            name='przech_zdjecie',
            field=models.FileField(blank=True, upload_to='magazyn', verbose_name='Zdjęcie 1'),
        ),
        migrations.AddField(
            model_name='elementkatalogowy',
            name='przech_zdjecie2',
            field=models.FileField(blank=True, upload_to='magazyn', verbose_name='Zdjęcie 2'),
        ),
        migrations.AddField(
            model_name='elementkatalogowy',
            name='przech_zdjecie3',
            field=models.FileField(blank=True, upload_to='magazyn', verbose_name='Zdjęcie 3'),
        ),
        migrations.AddField(
            model_name='elementkatalogowy',
            name='przech_zdjecie4',
            field=models.FileField(blank=True, upload_to='magazyn', verbose_name='Zdjęcie 4'),
        ),
        migrations.AddField(
            model_name='elementkatalogowy',
            name='uszkodz_zdjecie1',
            field=models.FileField(blank=True, upload_to='magazyn', verbose_name='Uszkodzenie 1'),
        ),
        migrations.AddField(
            model_name='elementkatalogowy',
            name='uszkodz_zdjecie2',
            field=models.FileField(blank=True, upload_to='magazyn', verbose_name='Uszkodzenie 2'),
        ),
        migrations.AddField(
            model_name='elementkatalogowy',
            name='uszkodz_zdjecie3',
            field=models.FileField(blank=True, upload_to='magazyn', verbose_name='Uszkodzenie 3'),
        ),
        migrations.AddField(
            model_name='elementkatalogowy',
            name='uszkodz_zdjecie4',
            field=models.FileField(blank=True, upload_to='magazyn', verbose_name='Uszkodzenie 4'),
        ),
        migrations.AddField(
            model_name='okresprzechowywania',
            name='ilosc_dni',
            field=models.IntegerField(default=0, verbose_name='Liczba dni'),
        ),
        migrations.AddField(
            model_name='okresprzechowywania',
            name='stawka',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=11, verbose_name='Stawka'),
        ),
        migrations.AddField(
            model_name='okresprzechowywania',
            name='stawka_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('DKK', 'DKK'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='EUR', editable=False, max_length=3),
        ),
    ]
