# Generated by Django 3.1.3 on 2025-03-29 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO_NEW', '0003_auto_20250329_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklad',
            name='czas_do',
            field=models.DateField(blank=True, null=True, verbose_name='Do daty'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='czas_od',
            field=models.DateField(blank=True, null=True, verbose_name='Od daty'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='do_skasowania',
            field=models.BooleanField(default=False, verbose_name='Skasować?'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='faktura',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Numer faktury'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='ilosc_dni',
            field=models.IntegerField(default=0, verbose_name='Liczba dni'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='liczyc',
            field=models.BooleanField(default=False, verbose_name='Pierwszy wpis do obliczeń'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='multi_uzycie',
            field=models.BooleanField(default=False, verbose_name='Element Wielokrotnego Użytku'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='multi_uzycie_id',
            field=models.BigIntegerField(default=0, verbose_name='MU ID'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='multi_uzycie_st',
            field=models.IntegerField(default=0, verbose_name='Ilość użycia'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='przech_gl',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=11, verbose_name='Głębokość [m]'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='przech_pow',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=11, verbose_name='Powierzchnia przechowywania [m²]'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='przech_sze',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=11, verbose_name='Szerokość [m]'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='przech_wys',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=11, verbose_name='Wysokość [m]'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='okres',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='COMP_REPO_NEW.okresprzechowywania', verbose_name='Okres przechowywania'),
        ),
    ]
