# Generated by Django 3.1.3 on 2025-03-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO_NEW', '0005_auto_20250329_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sklad',
            name='magazyn_opis',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Opis miejsca składowania'),
        ),
    ]
