# Generated by Django 3.1.3 on 2025-03-29 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO_NEW', '0006_auto_20250329_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='okresprzechowywania',
            name='ilosc_dni',
        ),
    ]
