# Generated by Django 3.1.3 on 2025-03-30 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO_NEW', '0007_remove_okresprzechowywania_ilosc_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sklad',
            name='blokada',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='flaga_op',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='multi_uzycie',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='multi_uzycie_id',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='multi_uzycie_st',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='status_pracy',
        ),
    ]
