# Generated by Django 3.1.3 on 2025-03-30 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO_NEW', '0008_auto_20250330_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sklad',
            name='do_skasowania',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='faktura',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='uwagi',
        ),
    ]
