# Generated by Django 3.1.3 on 2025-03-30 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO_NEW', '0009_auto_20250330_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sklad',
            name='data_modyfikacji',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='data_utworzenia',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='utworzony_przez',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='zmodyfikowany_przez',
        ),
    ]
