# Generated by Django 3.1.3 on 2025-03-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO_NEW', '0010_auto_20250330_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklad',
            name='uwagi',
            field=models.TextField(blank=True, verbose_name='Adnotacje'),
        ),
    ]
