# Generated by Django 3.1.3 on 2025-03-30 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO_NEW', '0011_sklad_uwagi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementkatalogowy',
            name='wysokosc',
        ),
        migrations.RemoveField(
            model_name='elementkatalogowy',
            name='zdjecie',
        ),
    ]
