# Generated by Django 3.1.3 on 2025-03-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO_NEW', '0012_auto_20250330_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementkatalogowy',
            name='wysokosc',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=11, verbose_name='Wysokość [m]'),
        ),
    ]
