# Generated by Django 3.1.3 on 2025-04-01 22:44

import COMP_REPO_NEW.models
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ORDERS', '0089_auto_20250106_2108'),
        ('COMP_REPO_NEW', '0014_auto_20250401_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementKatalogowy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, verbose_name='Nazwa elementu')),
                ('opis', models.TextField(blank=True, verbose_name='Opis elementu')),
                ('szerokosc', models.DecimalField(decimal_places=1, default=0.0, max_digits=11, verbose_name='Szerokość [m]')),
                ('glebokosc', models.DecimalField(decimal_places=1, default=0.0, max_digits=11, verbose_name='Głębokość [m]')),
                ('wysokosc', models.DecimalField(decimal_places=1, default=0.0, max_digits=11, verbose_name='Wysokość [m]')),
                ('powierzchnia', models.DecimalField(decimal_places=1, default=0.0, max_digits=11, verbose_name='Powierzchnia [m²]')),
                ('przech_zdjecie', models.FileField(blank=True, upload_to='magazyn', verbose_name='Zdjęcie 1')),
                ('przech_zdjecie2', models.FileField(blank=True, upload_to='magazyn', verbose_name='Zdjęcie 2')),
                ('przech_zdjecie3', models.FileField(blank=True, upload_to='magazyn', verbose_name='Zdjęcie 3')),
                ('przech_zdjecie4', models.FileField(blank=True, upload_to='magazyn', verbose_name='Zdjęcie 4')),
                ('uszkodz_zdjecie1', models.FileField(blank=True, upload_to='magazyn', verbose_name='Uszkodzenie 1')),
                ('uszkodz_zdjecie2', models.FileField(blank=True, upload_to='magazyn', verbose_name='Uszkodzenie 2')),
                ('uszkodz_zdjecie3', models.FileField(blank=True, upload_to='magazyn', verbose_name='Uszkodzenie 3')),
                ('uszkodz_zdjecie4', models.FileField(blank=True, upload_to='magazyn', verbose_name='Uszkodzenie 4')),
                ('aktywny', models.BooleanField(default=True, verbose_name='Element aktywny')),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Element katalogowy',
                'verbose_name_plural': 'Elementy katalogowe',
                'ordering': ['firma', 'nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(blank=True, default='', max_length=100, verbose_name='Nazwa firmy')),
                ('aktywna', models.BooleanField(default=True, verbose_name='Firma aktywna')),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmy',
            },
        ),
        migrations.CreateModel(
            name='OkresPrzechowywania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(blank=True, max_length=100, verbose_name='Nazwa okresu')),
                ('data_od', models.DateField(verbose_name='Od daty')),
                ('data_do', models.DateField(verbose_name='Do daty')),
                ('stawka_currency', djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('DKK', 'DKK'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='EUR', editable=False, max_length=3)),
                ('stawka', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=11, verbose_name='Stawka')),
                ('zamkniety', models.BooleanField(default=False, verbose_name='Okres zamknięty')),
                ('faktura', models.CharField(blank=True, default='', max_length=100, verbose_name='Numer faktury')),
                ('suma_kosztow_currency', djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('DKK', 'DKK'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='EUR', editable=False, max_length=3)),
                ('suma_kosztow', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=11, verbose_name='Suma kosztów w okresie')),
                ('suma_powierzchni', models.DecimalField(decimal_places=1, default=0.0, max_digits=11, verbose_name='Suma powierzchni [m²]')),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('data_modyfikacji', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COMP_REPO_NEW.firma', verbose_name='Firma')),
            ],
            options={
                'verbose_name': 'Okres przechowywania',
                'verbose_name_plural': 'Okresy przechowywania',
                'ordering': ['-data_od'],
            },
        ),
        migrations.CreateModel(
            name='Sklad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magazyn', models.CharField(choices=[('Wysogotowo', 'Wysogotowo'), ('Podolany', 'Podolany'), ('Jarocin', 'Jarocin')], default='Podolany', max_length=50, verbose_name='Miejsce składowania')),
                ('magazyn_opis', models.CharField(blank=True, default='', max_length=100, verbose_name='Opis miejsca składowania')),
                ('przech_nazwa', models.CharField(blank=True, default='', max_length=100, verbose_name='Nazwa towaru')),
                ('przech_nrpalet', models.CharField(blank=True, default='', max_length=100, verbose_name='Numer palety')),
                ('przech_sze', models.DecimalField(decimal_places=1, default=0.0, max_digits=11, verbose_name='Szerokość [m]')),
                ('przech_gl', models.DecimalField(decimal_places=1, default=0.0, max_digits=11, verbose_name='Głębokość [m]')),
                ('przech_wys', models.DecimalField(decimal_places=1, default=0.0, max_digits=11, verbose_name='Wysokość [m]')),
                ('przech_pow', models.DecimalField(decimal_places=1, default=0.0, max_digits=11, verbose_name='Powierzchnia przechowywania [m²]')),
                ('wydano_ilosc', models.IntegerField(default=0, verbose_name='Ile wydano')),
                ('wydano_data', models.DateField(blank=True, null=True, verbose_name='Data wydania')),
                ('zwroco_ilosc', models.IntegerField(default=0, verbose_name='Ile zwrócono')),
                ('zwroco_data', models.DateField(blank=True, null=True, verbose_name='Data powrotu')),
                ('zwroco_uwagi', models.TextField(blank=True, verbose_name='Zwroty - Uwagi')),
                ('czas_od', models.DateField(blank=True, null=True, verbose_name='Od daty')),
                ('czas_do', models.DateField(blank=True, null=True, verbose_name='Do daty')),
                ('ilosc_dni', models.IntegerField(default=0, verbose_name='Liczba dni')),
                ('stawka_currency', djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('DKK', 'DKK'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='EUR', editable=False, max_length=3)),
                ('stawka', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=11, verbose_name='Stawka')),
                ('koszt_przech_currency', djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('DKK', 'DKK'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='EUR', editable=False, max_length=3)),
                ('koszt_przech', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=11, verbose_name='Koszty przechowywania')),
                ('suma_currency', djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('DKK', 'DKK'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='EUR', editable=False, max_length=3)),
                ('suma', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=11, verbose_name='Suma Kosztów')),
                ('suma_pow', models.DecimalField(decimal_places=1, default=0.0, max_digits=11, verbose_name='Całkowita powierzchnia [m²]')),
                ('suma_zw_currency', djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('DKK', 'DKK'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='EUR', editable=False, max_length=3)),
                ('suma_zw', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=11, verbose_name='Suma Zwolnień')),
                ('suma_np_currency', djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('DKK', 'DKK'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='EUR', editable=False, max_length=3)),
                ('suma_np', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=11, verbose_name='Suma nie przypisanych')),
                ('zwolnione', models.BooleanField(default=False, verbose_name='Zwolnione')),
                ('blokada_zapisu', models.BooleanField(default=False, verbose_name='Blokada zapisu')),
                ('dok_pdf1', models.FileField(blank=True, upload_to='magazyn', verbose_name='Lista do przechowywania1')),
                ('dok_pdf2', models.FileField(blank=True, upload_to='magazyn', verbose_name='Lista do przechowywania2')),
                ('dok_pdf3', models.FileField(blank=True, upload_to='magazyn', verbose_name='Lista do przechowywania3')),
                ('dok_pdf4', models.FileField(blank=True, upload_to='magazyn', verbose_name='Lista do przechowywania4')),
                ('fv_pdf1', models.FileField(blank=True, upload_to='magazyn', verbose_name='Faktura')),
                ('uwagi', models.TextField(blank=True, verbose_name='Adnotacje')),
                ('liczyc', models.BooleanField(default=False, verbose_name='Pierwszy wpis do obliczeń')),
                ('element_katalogowy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='COMP_REPO_NEW.elementkatalogowy', verbose_name='Element z katalogu')),
                ('firma', models.ForeignKey(default=COMP_REPO_NEW.models.get_default_firma, on_delete=django.db.models.deletion.CASCADE, to='COMP_REPO_NEW.firma', verbose_name='Firma')),
                ('nr_sde', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skladowane_elementy', to='ORDERS.nrsde', verbose_name='Stoisko')),
                ('okres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='COMP_REPO_NEW.okresprzechowywania', verbose_name='Okres przechowywania')),
            ],
            options={
                'verbose_name': 'Sklad',
                'verbose_name_plural': 'Sklady',
                'ordering': ['firma', 'nr_sde', 'przech_nazwa'],
            },
        ),
        migrations.CreateModel(
            name='HistoriaPalety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_palety', models.CharField(max_length=100, verbose_name='Numer palety')),
                ('data_zmiany', models.DateTimeField(auto_now_add=True, verbose_name='Data zmiany')),
                ('zmieniajacy', models.CharField(blank=True, max_length=100, verbose_name='Osoba zmieniająca')),
                ('sklad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historia_palet', to='COMP_REPO_NEW.sklad')),
            ],
            options={
                'verbose_name': 'Historia palety',
                'verbose_name_plural': 'Historie palet',
                'ordering': ['-data_zmiany'],
            },
        ),
        migrations.AddField(
            model_name='elementkatalogowy',
            name='firma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COMP_REPO_NEW.firma', verbose_name='Firma'),
        ),
    ]
