# Generated by Django 3.1.3 on 2025-04-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO_NEW', '0015_auto_20250401_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='okresprzechowywania',
            name='zwolnione',
            field=models.BooleanField(default=False, verbose_name='Zwolnione'),
        ),
    ]
