# Generated by Django 3.1.3 on 2025-04-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO_NEW', '0017_sklad_flaga_op'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklad',
            name='status_pracy',
            field=models.IntegerField(default=0, verbose_name='Status Pracy'),
        ),
    ]
