# Generated by Django 3.1.3 on 2025-04-13 16:05

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO_NEW', '0018_sklad_status_pracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklad',
            name='suma_1m',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=11, verbose_name='Suma za 1 m-c'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='suma_1m_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('DKK', 'DKK'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='EUR', editable=False, max_length=3),
        ),
    ]
