# Generated by Django 3.1.3 on 2025-04-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO_NEW', '0019_auto_20250413_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementkatalogowy',
            name='licznik',
            field=models.IntegerField(default=0, verbose_name='Licznik użyć'),
        ),
        migrations.AddField(
            model_name='elementkatalogowy',
            name='wydany',
            field=models.BooleanField(default=False, verbose_name='Element wydany'),
        ),
    ]
