# Generated by Django 3.1.3 on 2025-04-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO_NEW', '0021_elementkatalogowy_zwolnione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementkatalogowy',
            name='zwolnione',
            field=models.BooleanField(default=False, verbose_name='Nie liczone'),
        ),
    ]
