# Generated by Django 3.1.3 on 2025-05-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO_NEW', '0022_auto_20250420_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementkatalogowy',
            name='aktywny',
            field=models.BooleanField(default=True, verbose_name='Element na liście'),
        ),
        migrations.AlterField(
            model_name='elementkatalogowy',
            name='zwolnione',
            field=models.BooleanField(default=False, verbose_name='Zwolnione'),
        ),
    ]
