# Generated by Django 3.1.3 on 2025-05-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO_NEW', '0023_auto_20250511_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='okresprzechowywania',
            name='stan',
            field=models.IntegerField(default=0, verbose_name='Stan okresu'),
        ),
    ]
