# Generated by Django 3.1.3 on 2025-05-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO_NEW', '0024_okresprzechowywania_stan'),
    ]

    operations = [
        migrations.AddField(
            model_name='okresprzechowywania',
            name='fv_pdf',
            field=models.FileField(blank=True, upload_to='magazyn', verbose_name='Faktura'),
        ),
    ]
