# Generated by Django 3.1.3 on 2025-05-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO_NEW', '0025_okresprzechowywania_fv_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okresprzechowywania',
            name='fv_pdf',
            field=models.FileField(blank=True, upload_to='magazyn_fv', verbose_name='Faktura'),
        ),
    ]
