# Generated by Django 2.2.3 on 2019-07-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='img1',
            field=models.FileField(blank=True, upload_to='dokuments', verbose_name='Skan'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='img2',
            field=models.FileField(blank=True, upload_to='dokuments', verbose_name='Skan'),
        ),
    ]
