# Generated by Django 2.2.3 on 2020-03-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARS', '0002_auto_20190706_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='stp',
            field=models.IntegerField(default=0, verbose_name='Status przeglądu'),
        ),
        migrations.AddField(
            model_name='auto',
            name='stu',
            field=models.IntegerField(default=0, verbose_name='Status ubezpieczenia '),
        ),
    ]
