# Generated by Django 2.2.3 on 2020-04-09 22:59

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CARS', '0003_auto_20200322_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='arch',
            field=models.BooleanField(default=False, verbose_name='Sprzet Archiwalny'),
        ),
        migrations.AddField(
            model_name='auto',
            name='drl',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data rozp. leasingu'),
        ),
        migrations.AddField(
            model_name='auto',
            name='dzl',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data zakon. leasingu'),
        ),
        migrations.AddField(
            model_name='auto',
            name='nul',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nr umowy leasingu'),
        ),
        migrations.AddField(
            model_name='auto',
            name='rul',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Rata leasingu'),
        ),
        migrations.AddField(
            model_name='auto',
            name='rul_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar\xa0Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski Nowy')], default='PLN', editable=False, max_length=3),
        ),
    ]
