# Generated by Django 2.2.3 on 2020-04-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARS', '0004_auto_20200409_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='stdrl',
            field=models.IntegerField(default=0, verbose_name='Status data leasing start '),
        ),
        migrations.AddField(
            model_name='auto',
            name='stdzl',
            field=models.IntegerField(default=0, verbose_name='Status data leasing koniec'),
        ),
    ]
