# Generated by Django 2.2.3 on 2020-04-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARS', '0005_auto_20200409_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='rodzaj',
            field=models.CharField(choices=[('AUTO', 'Auto'), ('WUWI', 'Wózek widłowy'), ('INNY', 'Inny sprzęt')], default='AUTO', max_length=100, verbose_name='Rodzaj pojazdu'),
        ),
    ]
