# Generated by Django 2.2.3 on 2020-04-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARS', '0006_auto_20200424_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='imie',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='nazwisko',
        ),
        migrations.AddField(
            model_name='auto',
            name='imie_n',
            field=models.CharField(blank=True, max_length=100, verbose_name='Imię i Nazwisko'),
        ),
        migrations.AddField(
            model_name='auto',
            name='opis',
            field=models.CharField(blank=True, max_length=200, verbose_name='Opis/Lokalizacja'),
        ),
    ]
