# Generated by Django 3.1.3 on 2021-05-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARS', '0008_auto_20200628_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='koniecl',
            field=models.BooleanField(default=False, verbose_name='Koniec Leasingu'),
        ),
    ]
