# Generated by Django 3.1.3 on 2021-05-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARS', '0009_auto_koniecl'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='sprzedany',
            field=models.BooleanField(default=False, verbose_name='Sprzedany'),
        ),
    ]
