# Generated by Django 3.1.3 on 2022-01-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARS', '0010_auto_sprzedany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='img1',
            field=models.FileField(blank=True, upload_to='cars', verbose_name='Skan'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='img2',
            field=models.FileField(blank=True, upload_to='cars', verbose_name='Skan'),
        ),
    ]
