# Generated by Django 3.1.3 on 2023-05-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARS', '0012_auto_deleg_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='pt',
            field=models.DateField(blank=True, null=True, verbose_name='Data przeglądu tachometru'),
        ),
        migrations.AddField(
            model_name='auto',
            name='spt',
            field=models.IntegerField(default=0, verbose_name='Status przeglądu tachometru'),
        ),
    ]
