# Generated by Django 5.0 on 2023-12-16 20:14

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CARS', '0013_auto_20230506_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='rul_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('DKK', 'DKK'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
    ]
