# Generated by Django 3.1.3 on 2023-01-08 07:46

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ORDERS', '0062_nrmpk_lsde'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazyn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('przech_nazwa', models.CharField(blank=True, default='', max_length=100, verbose_name='Nazwa')),
                ('przech_zdjecie', models.FileField(blank=True, upload_to='images', verbose_name='Zdjęcie')),
                ('przech_pow', models.IntegerField(default=0, verbose_name='Powierzchnia przechowywania')),
                ('wydano_ilosc', models.IntegerField(default=0, verbose_name='Ilość wydano')),
                ('wydano_data', models.DateField(blank=True, null=True, verbose_name='Data wydania')),
                ('zwroco_ilosc', models.IntegerField(default=0, verbose_name='Ilość zwrócono')),
                ('zwroco_data', models.DateField(blank=True, null=True, verbose_name='Data zwrócenia')),
                ('zwroco_uwagi', models.TextField(blank=True, verbose_name='Uwagi')),
                ('czas_od', models.DateField(blank=True, null=True, verbose_name='Czas od')),
                ('czas_do', models.DateField(blank=True, null=True, verbose_name='Czas do')),
                ('miejsce_sklad', models.CharField(choices=[('MAGAZYN1', 'MAGAZYN Szparagowa'), ('MAGAZYN2', 'MAGAZYN Podolany'), ('MAGAZYN3', 'MAGAZYN3.')], default='MAGAZYN1', max_length=50, verbose_name='Miejsce składowania')),
                ('koszt_przech_currency', djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3)),
                ('koszt_przech', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Koszty przechowywania')),
                ('nr_sde', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ORDERS.nrsde', verbose_name='Stoisko')),
            ],
            options={
                'verbose_name': 'Magazyn',
                'verbose_name_plural': 'Magazyny',
            },
        ),
    ]
