# Generated by Django 3.1.3 on 2023-01-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazyn',
            name='przech_zdjecie',
            field=models.FileField(blank=True, upload_to='magazyn', verbose_name='Zdjęcie'),
        ),
    ]
