# Generated by Django 3.1.3 on 2023-01-09 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0002_auto_20230108_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magazyn',
            old_name='miejsce_sklad',
            new_name='magazyn',
        ),
    ]
