# Generated by Django 3.1.3 on 2023-01-09 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0062_nrmpk_lsde'),
        ('COMP_REPO', '0003_auto_20230109_1050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Magazyn',
            new_name='Sklad',
        ),
    ]
