# Generated by Django 3.1.3 on 2023-01-09 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0004_auto_20230109_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sklad',
            options={'verbose_name': 'Sklad', 'verbose_name_plural': 'Sklady'},
        ),
    ]
