# Generated by Django 3.1.3 on 2023-01-09 12:08

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0005_auto_20230109_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklad',
            name='suma',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Suma Kosztów'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='suma_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
    ]
