# Generated by Django 3.1.3 on 2023-01-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0006_auto_20230109_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sklad',
            name='przech_zdjecie',
            field=models.FileField(blank=True, upload_to='comp_repo', verbose_name='Zdjęcie'),
        ),
    ]
