# Generated by Django 3.1.3 on 2023-01-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0007_auto_20230109_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sklad',
            name='przech_zdjecie',
            field=models.FileField(blank=True, upload_to='magazyn', verbose_name='Zdjęcie'),
        ),
    ]
