# Generated by Django 3.1.3 on 2023-01-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0008_auto_20230109_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sklad',
            name='przech_nazwa',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nazwa towaru'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='zwroco_data',
            field=models.DateField(blank=True, null=True, verbose_name='Data powrotu'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='zwroco_uwagi',
            field=models.TextField(blank=True, verbose_name='Zwroty - Uwagi'),
        ),
    ]
