# Generated by Django 3.1.3 on 2023-01-14 07:43

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0009_auto_20230109_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklad',
            name='przech_gl',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=11, verbose_name='Głebokość'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='przech_nrpalet',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Numer palety'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='przech_sze',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=11, verbose_name='Szerokość'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='przech_wys',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=11, verbose_name='Wysokość'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='stawka',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=11, verbose_name='Stawka'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='stawka_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='koszt_przech',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=11, verbose_name='Koszty przechowywania'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='koszt_przech_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='suma',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=11, verbose_name='Suma Kosztów'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='suma_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='EUR', editable=False, max_length=3),
        ),
    ]
