# Generated by Django 3.1.3 on 2023-01-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0010_auto_20230114_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sklad',
            name='przech_pow',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=11, verbose_name='Powierzchnia przechowywania'),
        ),
    ]
