# Generated by Django 3.1.3 on 2023-01-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0012_auto_20230114_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklad',
            name='przech_zdjecie2',
            field=models.FileField(blank=True, upload_to='magazyn', verbose_name='Zdjęcie2'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='przech_zdjecie',
            field=models.FileField(blank=True, upload_to='magazyn', verbose_name='Zdjęcie1'),
        ),
    ]
