# Generated by Django 3.1.3 on 2023-01-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0013_auto_20230129_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklad',
            name='uszkodz_zdjecie1',
            field=models.FileField(blank=True, upload_to='magazyn', verbose_name='Uszkodzenie 1'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='uszkodz_zdjecie2',
            field=models.FileField(blank=True, upload_to='magazyn', verbose_name='Uszkodzenie 2'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='uszkodz_zdjecie3',
            field=models.FileField(blank=True, upload_to='magazyn', verbose_name='Uszkodzenie 3'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='uszkodz_zdjecie4',
            field=models.FileField(blank=True, upload_to='magazyn', verbose_name='Uszkodzenie 4'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='przech_zdjecie',
            field=models.FileField(blank=True, upload_to='magazyn', verbose_name='Zdjęcie 1'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='przech_zdjecie2',
            field=models.FileField(blank=True, upload_to='magazyn', verbose_name='Zdjęcie 2'),
        ),
    ]
