# Generated by Django 3.1.3 on 2023-02-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0014_auto_20230129_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sklad',
            name='magazyn',
            field=models.CharField(choices=[('Szparagowa', 'MAGAZYN Szparagowa'), ('Podolany', 'MAGAZYN Podolany'), ('MAGAZYN3', 'MAGAZYN3.')], default='Szparagowa', max_length=50, verbose_name='Miejsce składowania'),
        ),
    ]
