# Generated by Django 3.1.3 on 2023-03-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0015_auto_20230213_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklad',
            name='suma_pow',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=11, verbose_name='Całkowita powierzchnia [m²]'),
        ),
    ]
