# Generated by Django 3.1.3 on 2023-03-29 11:50

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0016_sklad_suma_pow'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklad',
            name='faktura',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=11, verbose_name='Faktura'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='faktura_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='sklad',
            name='zwolnione',
            field=models.BooleanField(default=False, verbose_name='Zwolnione'),
        ),
    ]
