# Generated by Django 3.1.3 on 2023-03-29 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0017_auto_20230329_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sklad',
            name='faktura',
        ),
        migrations.RemoveField(
            model_name='sklad',
            name='faktura_currency',
        ),
    ]
