# Generated by Django 3.1.3 on 2023-03-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0018_auto_20230329_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklad',
            name='faktura',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Numer faktury'),
        ),
    ]
