# Generated by Django 3.1.3 on 2023-03-29 13:27

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0020_auto_20230329_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklad',
            name='suma_np',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=11, verbose_name='Suma nie przypisanych'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='suma_np_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='EUR', editable=False, max_length=3),
        ),
    ]
