# Generated by Django 3.1.3 on 2023-04-02 20:18

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0021_auto_20230329_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sklad',
            name='koszt_przech_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('DKK', 'DKK'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='EUR', editable=False, max_length=3),
        ),
    ]
