# Generated by Django 3.1.3 on 2023-06-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0022_auto_20230402_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklad',
            name='flaga_op',
            field=models.IntegerField(default=0, verbose_name='Flaga operacji'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Status'),
        ),
    ]
