# Generated by Django 3.1.3 on 2023-12-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0023_auto_20230604_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklad',
            name='status_pracy',
            field=models.BooleanField(default=False, verbose_name='Status pracy'),
        ),
    ]
