# Generated by Django 5.0 on 2023-12-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0025_alter_sklad_stawka_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sklad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
