# Generated by Django 3.1.3 on 2024-01-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0031_auto_20240101_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklad',
            name='blokada',
            field=models.BooleanField(default=False, verbose_name='Blokada daty'),
        ),
    ]
