# Generated by Django 3.1.3 on 2024-01-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0032_sklad_blokada'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklad',
            name='blokada_zapisu',
            field=models.BooleanField(default=False, verbose_name='Blokada zapisu'),
        ),
    ]
