# Generated by Django 5.0 on 2024-03-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0033_sklad_blokada_zapisu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sklad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
