# Generated by Django 5.0 on 2024-03-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0034_alter_sklad_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklad',
            name='przech_zdjecie3',
            field=models.FileField(blank=True, upload_to='magazyn', verbose_name='Zdjęcie 3'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='przech_zdjecie4',
            field=models.FileField(blank=True, upload_to='magazyn', verbose_name='Zdjęcie 4'),
        ),
    ]
