# Generated by Django 5.0 on 2024-03-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0035_sklad_przech_zdjecie3_sklad_przech_zdjecie4'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklad',
            name='multi_uzycie',
            field=models.BooleanField(default=False, verbose_name='Wielokrotne użycie'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='multi_uzycie_id',
            field=models.BigIntegerField(default=0, verbose_name='MU ID'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='multi_uzycie_st',
            field=models.IntegerField(default=0, verbose_name='Ilość użycia'),
        ),
    ]
