# Generated by Django 3.1.3 on 2024-03-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0036_sklad_multi_uzycie_sklad_multi_uzycie_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sklad',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
