# Generated by Django 5.0 on 2024-04-15 07:49

import COMP_REPO.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0038_firma_alter_sklad_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklad',
            name='firma',
            field=models.ForeignKey(blank=True, default=COMP_REPO.models.get_default_firma, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='COMP_REPO.firma', verbose_name='Firma'),
        ),
    ]
