# Generated by Django 5.0 on 2024-04-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0040_auto_20240417_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklad',
            name='magazyn_opis',
            field=models.CharField(default='', max_length=100, verbose_name='Miejsce składowania'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='magazyn',
            field=models.CharField(choices=[('Wysogotowo', 'Wysogotowo'), ('Podolany', 'Podolany'), ('Jarocin', 'Jarocin')], default='Podolany', max_length=50, verbose_name='Miejsce składowania'),
        ),
    ]
