# Generated by Django 5.0 on 2024-09-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0043_alter_firma_id_alter_sklad_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklad',
            name='Uwagi',
            field=models.TextField(blank=True, verbose_name='Uwagi'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='dok_pdf1',
            field=models.FileField(blank=True, upload_to='magazyn', verbose_name='Dokument 1'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='dok_pdf2',
            field=models.FileField(blank=True, upload_to='magazyn', verbose_name='Dokument 2'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='dok_pdf3',
            field=models.FileField(blank=True, upload_to='magazyn', verbose_name='Dokument 3'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='dok_pdf4',
            field=models.FileField(blank=True, upload_to='magazyn', verbose_name='Dokument 4'),
        ),
    ]
