# Generated by Django 5.0 on 2024-09-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0044_sklad_uwagi_sklad_dok_pdf1_sklad_dok_pdf2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sklad',
            old_name='Uwagi',
            new_name='uwagi',
        ),
    ]
