# Generated by Django 5.0 on 2024-09-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0045_rename_uwagi_sklad_uwagi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sklad',
            name='uwagi',
            field=models.TextField(blank=True, verbose_name='Uwagi (Darek)'),
        ),
    ]
