# Generated by Django 3.1.3 on 2024-10-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0049_auto_20240930_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklad',
            name='do_skasowania',
            field=models.BooleanField(default=False, verbose_name='Skasować?'),
        ),
    ]
