# Generated by Django 5.0 on 2024-11-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0050_sklad_do_skasowania'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklad',
            name='fv_pdf1',
            field=models.FileField(blank=True, upload_to='magazyn', verbose_name='Faktura'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
