# Generated by Django 3.1.3 on 2024-11-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0051_sklad_fv_pdf1_alter_firma_id_alter_sklad_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
