# Generated by Django 5.0 on 2024-12-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0053_alter_firma_id_alter_sklad_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklad',
            name='liczyc',
            field=models.BooleanField(default=False, verbose_name='Pierwszy wpis do obliczeń'),
        ),
    ]
