# Generated by Django 5.0 on 2024-12-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0055_sklad_ilosc_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sklad',
            name='multi_uzycie',
            field=models.BooleanField(default=False, verbose_name='Element Wielokrotnego Użytku'),
        ),
    ]
