# Generated by Django 5.0 on 2025-02-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0061_auto_20250126_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklad',
            name='dok_pdf2',
            field=models.FileField(blank=True, upload_to='magazyn', verbose_name='Lista do przechowywania2'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='dok_pdf3',
            field=models.FileField(blank=True, upload_to='magazyn', verbose_name='Lista do przechowywania3'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='dok_pdf4',
            field=models.FileField(blank=True, upload_to='magazyn', verbose_name='Lista do przechowywania4'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='dok_pdf1',
            field=models.FileField(blank=True, upload_to='magazyn', verbose_name='Lista do przechowywania1'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
