# Generated by Django 3.1.3 on 2025-02-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP_REPO', '0062_sklad_dok_pdf2_sklad_dok_pdf3_sklad_dok_pdf4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
