# Generated by Django 2.2.3 on 2019-07-06 02:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dowod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100, verbose_name='Imię')),
                ('nazwisko', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('img1', models.FileField(blank=True, upload_to='dokuments', verbose_name='Zdjęcie')),
                ('img2', models.FileField(blank=True, upload_to='dokuments', verbose_name='Zdjęcie')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data wprowadzenia')),
                ('uwagi', models.TextField(blank=True, verbose_name='Uwagi')),
            ],
            options={
                'verbose_name': 'Dowod',
                'verbose_name_plural': 'Dowody',
            },
        ),
    ]
