# Generated by Django 3.1.3 on 2022-01-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ID_CARDS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dowod',
            name='img1',
            field=models.FileField(blank=True, upload_to='documents', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='dowod',
            name='img2',
            field=models.FileField(blank=True, upload_to='documents', verbose_name='Zdjęcie'),
        ),
    ]
