# Generated by Django 5.0 on 2023-12-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ID_CARDS', '0004_alter_dowod_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dowod',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
