# Generated by Django 5.0 on 2024-04-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ID_CARDS', '0008_auto_20240101_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dowod',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
