# Generated by Django 2.2.3 on 2020-01-04 15:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HIP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprzet',
            name='arch',
            field=models.BooleanField(default=False, verbose_name='Konfiguracja Archiwalna'),
        ),
        migrations.AddField(
            model_name='sprzet',
            name='gw',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Termin Gwarancji'),
        ),
        migrations.AlterField(
            model_name='sprzet',
            name='system',
            field=models.ForeignKey(max_length=400, on_delete=django.db.models.deletion.CASCADE, to='HIP.System', verbose_name='Dział'),
        ),
    ]
