# Generated by Django 2.2.3 on 2020-01-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIP', '0002_auto_20200104_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprzet',
            name='doc',
            field=models.FileField(blank=True, upload_to='dokuments', verbose_name='Dokument'),
        ),
    ]
