# Generated by Django 2.2.3 on 2020-02-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIP', '0003_sprzet_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprzet',
            name='docz',
            field=models.FileField(blank=True, upload_to='dokuments', verbose_name='Dokument zdania'),
        ),
        migrations.AlterField(
            model_name='sprzet',
            name='doc',
            field=models.FileField(blank=True, upload_to='dokuments', verbose_name='Dokument przyjęcia'),
        ),
    ]
