# Generated by Django 2.2.3 on 2020-02-03 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HIP', '0005_auto_20200203_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprzet',
            name='pr',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data przyjęcia'),
        ),
    ]
