# Generated by Django 2.2.3 on 2020-02-09 04:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HIP', '0006_sprzet_pr'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprzet',
            name='pz',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data zdania'),
        ),
    ]
