# Generated by Django 2.2.3 on 2020-04-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIP', '0007_sprzet_pz'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprzet',
            name='mag',
            field=models.BooleanField(default=False, verbose_name='Magazyn'),
        ),
    ]
