# Generated by Django 2.2.3 on 2020-08-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIP', '0009_auto_20200628_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprzet',
            name='stan',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='Stan sprzętu (0...3; 3-max)'),
        ),
    ]
