# Generated by Django 2.2.3 on 2020-08-22 16:54

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('HIP', '0010_auto_20200816_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprzet',
            name='wartosc',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Wartość'),
        ),
        migrations.AddField(
            model_name='sprzet',
            name='wartosc_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar\xa0Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski Nowy')], default='PLN', editable=False, max_length=3),
        ),
    ]
