# Generated by Django 2.2.3 on 2020-08-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIP', '0014_auto_20200830_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprzet',
            name='stan',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='Stan sprzętu (0...4; 4-max)'),
        ),
    ]
