# Generated by Django 3.1.3 on 2021-02-14 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HIP', '0016_auto_20200903_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprzet',
            name='snm',
        ),
        migrations.RemoveField(
            model_name='sprzet',
            name='typm',
        ),
    ]
