# Generated by Django 3.1.3 on 2021-02-14 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIP', '0017_auto_20210214_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='fv',
            field=models.FileField(blank=True, upload_to='images', verbose_name='Faktura'),
        ),
    ]
