# Generated by Django 3.1.3 on 2021-03-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIP', '0018_profil_fv'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprzet',
            name='sprzedany',
            field=models.BooleanField(default=False, verbose_name='Sprzedany'),
        ),
    ]
