# Generated by Django 3.1.3 on 2021-03-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIP', '0019_sprzet_sprzedany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprzet',
            name='host',
            field=models.CharField(choices=[('Komputer', 'Komputer'), ('Monitor', 'Monitor'), ('Drukarka', 'Drukarka'), ('Serwer', 'Serwer'), ('Access Point', 'Access Point'), ('Router', 'Router'), ('Switch', 'Switch'), ('Domena', 'Domena'), ('Tablet', 'Tablet'), ('Czytnik', 'Czytnik'), ('Inne', 'Inne')], default='Komputer', max_length=100, verbose_name='Host'),
        ),
    ]
