# Generated by Django 3.1.3 on 2021-03-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIP', '0020_auto_20210327_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprzet',
            name='host',
            field=models.CharField(choices=[('Komputer', 'Komputer'), ('Monitor', 'Monitor'), ('Drukarka', 'Drukarka'), ('Serwer', 'Serwer'), ('Access Point', 'Access Point'), ('Router', 'Router'), ('Switch', 'Switch'), ('Domena', 'Domena'), ('Tablet', 'Tablet'), ('Czytnik', 'Czytnik'), ('VOIP', 'VOIP'), ('Inne', 'Inne')], default='Komputer', max_length=100, verbose_name='Host'),
        ),
    ]
