# Generated by Django 3.1.3 on 2021-12-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIP', '0021_auto_20210328_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='data_waznosci',
            field=models.DateField(blank=True, null=True, verbose_name='Data ważności licencji'),
        ),
    ]
