# Generated by Django 3.1.3 on 2021-12-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIP', '0022_profil_data_waznosci'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='termin',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='Termin'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='data_waznosci',
            field=models.DateField(blank=True, null=True, verbose_name='Data ważności (Puste - jeśli licencja stała)'),
        ),
    ]
