# Generated by Django 3.1.3 on 2021-12-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIP', '0023_auto_20211229_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='auto_platnosc',
            field=models.CharField(choices=[('NIE', 'NIE'), ('TAK', 'TAK')], default='NIE', max_length=10, verbose_name='Auto płatność'),
        ),
    ]
