# Generated by Django 3.1.3 on 2021-12-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIP', '0024_profil_auto_platnosc'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='karta',
            field=models.CharField(blank=True, max_length=150, verbose_name='Karta płatnicza'),
        ),
    ]
