# Generated by Django 3.1.3 on 2023-12-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIP', '0027_auto_20220105_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprzet',
            name='opis',
            field=models.TextField(blank=True, verbose_name='Opis'),
        ),
    ]
