# Generated by Django 3.1.3 on 2023-12-14 18:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HIP', '0028_auto_20231214_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serwis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('problem', models.CharField(blank=True, max_length=450, verbose_name='Problem')),
                ('opis', models.TextField(blank=True, verbose_name='Opis')),
                ('uwagi', models.TextField(blank=True, verbose_name='Uwagi')),
                ('sprzet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HIP.sprzet', verbose_name='Sprzęt')),
            ],
            options={
                'verbose_name': 'Serwis',
                'verbose_name_plural': 'Serwisy',
            },
        ),
    ]
