# Generated by Django 3.1.3 on 2023-12-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIP', '0029_serwis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serwis',
            name='problem',
            field=models.TextField(blank=True, verbose_name='Problem'),
        ),
    ]
