# Generated by Django 5.0 on 2023-12-16 20:14
from django.db import models
#import ckeditor.fields
import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HIP', '0031_auto_20231216_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serwis',
            name='problem',
            field=models.TextField(blank=True, verbose_name='Problem'),
            #field=ckeditor.fields.RichTextField(blank=True, verbose_name='Problem'),
        ),
        migrations.AlterField(
            model_name='sprzet',
            name='wartosc_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('DKK', 'DKK'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
    ]
