# Generated by Django 3.1.3 on 2020-11-18 16:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienie',
            name='data_dost',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Data dostawy'),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='data_przeka',
            field=models.DateField(blank=True, verbose_name='Data przekazania księgowej'),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='nr_dok1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nr dokumentu 1'),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='nr_dok2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nr dokumentu 2'),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='nr_dok3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nr FV rozlicz.'),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='nr_fv',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nr faktury'),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='nr_mpk',
            field=models.ForeignKey(blank=True, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='ORDERS.nrmpk', verbose_name='Nr MPK'),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='nr_sde',
            field=models.ForeignKey(blank=True, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='ORDERS.nrsde', verbose_name='Nr SDE'),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='rodzaj_plat',
            field=models.CharField(blank=True, choices=[('-', '-'), ('Zaliczka', 'Zaliczka'), ('Proforma', 'Proforma')], default='-', max_length=100, verbose_name='Rodzaj platności'),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='sposob_plat',
            field=models.CharField(blank=True, choices=[('-', '-'), ('Przelew', 'Przelew'), ('Karta', 'Karta'), ('Gotówka', 'Gotówka')], default='-', max_length=100, verbose_name='Sposób płatności'),
        ),
    ]
