# Generated by Django 3.1.3 on 2020-11-18 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0002_auto_20201118_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienie',
            name='data_przeka',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Data przekazania księgowej'),
        ),
    ]
