# Generated by Django 3.1.3 on 2020-11-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0003_auto_20201118_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zamowienie',
            name='kontrola_currency',
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='kontrola',
            field=models.IntegerField(default=0, verbose_name='Kontrola'),
        ),
    ]
