# Generated by Django 3.1.3 on 2020-11-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0005_auto_20201123_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrmpk',
            name='opis',
            field=models.CharField(blank=True, max_length=500, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='nrmpk',
            name='nazwa',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nazwa'),
        ),
    ]
