# Generated by Django 3.1.3 on 2020-11-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0006_auto_20201126_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zamowienie',
            name='data_przeka',
        ),
        migrations.AddField(
            model_name='zamowienie',
            name='roz',
            field=models.BooleanField(default=False, verbose_name='Rozliczono'),
        ),
    ]
