# Generated by Django 3.1.3 on 2020-11-28 23:55

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0007_auto_20201127_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienie',
            name='kwota_brutto_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='kwota_netto_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='wartosc_zam_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='zal1_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='zal2_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='zal3_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski')], default='PLN', editable=False, max_length=3),
        ),
    ]
