# Generated by Django 3.1.3 on 2020-11-29 12:32

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0009_auto_20201129_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrsde',
            name='wartosc1',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Wartosc Brutto'),
        ),
        migrations.AddField(
            model_name='nrsde',
            name='wartosc1_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='nrsde',
            name='wartosc',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Wartosc Netto'),
        ),
    ]
