# Generated by Django 3.1.3 on 2020-12-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0011_auto_20201129_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='uwagi',
            field=models.TextField(blank=True, verbose_name='Uwagi'),
        ),
    ]
