# Generated by Django 3.1.4 on 2020-12-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0012_zamowienie_uwagi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nrmpk',
            options={'ordering': ['nazwa'], 'verbose_name': 'Numer MPK', 'verbose_name_plural': 'Numery MPK'},
        ),
        migrations.AlterModelOptions(
            name='nrsde',
            options={'ordering': ['nazwa'], 'verbose_name': 'Numer SDE', 'verbose_name_plural': 'Numery SDE'},
        ),
        migrations.AddField(
            model_name='nrsde',
            name='opis',
            field=models.CharField(blank=True, max_length=500, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='nrmpk',
            name='opis',
            field=models.CharField(blank=True, max_length=500, verbose_name='Opis'),
        ),
    ]
