# Generated by Django 3.1.4 on 2020-12-28 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0017_auto_20201228_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienie',
            name='data_dost',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data dostawy'),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='data_fv',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data faktury'),
        ),
    ]
