# Generated by Django 3.1.4 on 2020-12-28 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0019_auto_20201228_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienie',
            name='nr_mpk',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ORDERS.nrmpk', verbose_name='Nr MPK'),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='nr_sde',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ORDERS.nrsde', verbose_name='Nr SDE'),
        ),
    ]
