# Generated by Django 3.1.4 on 2021-01-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0020_auto_20201228_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nrmpk',
            name='rok',
            field=models.IntegerField(default=2021, verbose_name='Rok Nr MPK'),
        ),
        migrations.AlterField(
            model_name='nrsde',
            name='rok',
            field=models.IntegerField(default=2021, verbose_name='Rok Nr SDE'),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='rok',
            field=models.IntegerField(default=2021, verbose_name='Rok zamówienia'),
        ),
    ]
