# Generated by Django 3.1.4 on 2021-01-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0021_auto_20210101_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='inicjaly',
            field=models.CharField(blank=True, max_length=10, verbose_name='Inicjały'),
        ),
    ]
