# Generated by Django 3.1.5 on 2021-01-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0024_auto_20210114_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienie',
            name='sposob_plat',
            field=models.CharField(blank=True, choices=[('Przelew', 'Przelew'), ('Karta', 'Karta'), ('Gotówka', 'Gotówka')], default='-', max_length=100, verbose_name='Sposób płatności'),
        ),
    ]
