# Generated by Django 3.1.5 on 2021-01-15 17:27

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0026_auto_20210115_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nrmpk',
            name='wartosc',
        ),
        migrations.RemoveField(
            model_name='nrmpk',
            name='wartosc1',
        ),
        migrations.RemoveField(
            model_name='nrmpk',
            name='wartosc1_currency',
        ),
        migrations.RemoveField(
            model_name='nrmpk',
            name='wartosc_currency',
        ),
        migrations.AddField(
            model_name='nrmpk',
            name='sum_zal',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Suma zaliczek'),
        ),
        migrations.AddField(
            model_name='nrmpk',
            name='sum_zal_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='nrmpk',
            name='sum_zam',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Suma zamówień'),
        ),
        migrations.AddField(
            model_name='nrmpk',
            name='sum_zam_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
    ]
