# Generated by Django 3.1.5 on 2021-01-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0028_auto_20210115_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nrsde',
            name='opis',
            field=models.CharField(blank=True, max_length=500, verbose_name='Opis/Stoisko'),
        ),
    ]
