# Generated by Django 3.1.5 on 2021-01-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0030_auto_20210117_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nrsde',
            name='pm',
            field=models.CharField(blank=True, choices=[('Agnieszka Skóra', 'Agnieszka Skóra'), ('Julia Królak', 'Julia Królak'), ('Piotr Junik', 'Piotr Junik'), ('Karolina Gendera', 'Karolina Gendera'), ('Patryk Krajewski', 'Patryk Krajewski'), ('Dariusz Kaczmarek', 'Dariusz Kaczmarek'), ('Łukasz Jerzmanowski', 'Łukasz Jerzmanowski'), ('Michał Ogrzewalski', 'Michał Ogrzewalski'), ('Iwona Sawicka', 'Iwona Sawicka'), ('Marzena Michalska', 'Marzena Michalska'), ('Łukasz Zaremba', 'Łukasz Zaremba'), ('Joanna Dittmar', 'Joanna Dittmar'), ('Adam Beim', 'Adam Beim'), ('Eryk Przybyłowicz', 'Eryk Przybyłowicz'), ('Małgosia Świadek', 'Małgosia Świadek')], default='', max_length=500, verbose_name='Project Manager'),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='rodzaj_plat',
            field=models.CharField(blank=True, choices=[('Zaliczka', 'Zaliczka'), ('Proforma', 'Proforma'), ('Zamowienie', 'Zamówienie'), ('Faktura', 'Faktura'), ('Korekta', 'Korekta'), ('Nota', 'Nota')], default='', max_length=100, verbose_name='Rodzaj dokumentu'),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='sposob_plat',
            field=models.CharField(blank=True, choices=[('Przelew', 'Przelew'), ('Karta', 'Karta'), ('Gotówka', 'Gotówka')], default='', max_length=100, verbose_name='Sposób płatności'),
        ),
    ]
