# Generated by Django 3.1.5 on 2021-01-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0032_auto_20210124_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nrsde',
            name='miesiac',
        ),
        migrations.AddField(
            model_name='nrsde',
            name='c_miesiac',
            field=models.CharField(blank=True, max_length=500, verbose_name='Got. Miesiac'),
        ),
        migrations.AddField(
            model_name='nrsde',
            name='d_miesiac',
            field=models.CharField(blank=True, max_length=500, verbose_name='Bezp. Miesiac'),
        ),
    ]
