# Generated by Django 3.1.3 on 2021-01-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0033_auto_20210124_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrsde',
            name='rokk',
            field=models.IntegerField(default=2021, verbose_name='Rok kal Nr SDE'),
        ),
    ]
