# Generated by Django 3.1.3 on 2021-02-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0035_auto_20210214_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienie',
            name='rodzaj_plat',
            field=models.CharField(blank=True, choices=[('Zaliczka', 'Zaliczka'), ('Proforma', 'Proforma'), ('Zamowienie', 'Zamówienie'), ('Faktura', 'Faktura'), ('Korekta', 'Korekta'), ('Nota', 'Nota'), ('Polisa', 'Polisa'), ('Inny', 'Inny')], default='', max_length=100, verbose_name='Rodzaj dokumentu'),
        ),
    ]
