# Generated by Django 3.1.3 on 2021-02-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0036_auto_20210215_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrsde',
            name='rks',
            field=models.CharField(blank=True, max_length=50, verbose_name='Rok sprzedaży (z FV)'),
        ),
        migrations.AlterField(
            model_name='nrsde',
            name='mcs',
            field=models.CharField(blank=True, choices=[('styczeń', 'styczeń'), ('luty', 'luty'), ('marzec', 'marzec'), ('kwiecień', 'kwiecień'), ('maj', 'maj'), ('czerwiec', 'czerwiec'), ('lipiec', 'lipiec'), ('sierpień', 'sierpień'), ('wrzesień', 'wrzesień'), ('październik', 'październik'), ('listopad', 'listopad'), ('grudzień', 'grudzień')], default='', max_length=50, verbose_name='Miesiąc sprzedaży (z FV)'),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='rodzaj_plat',
            field=models.CharField(blank=True, choices=[('Zaliczka', 'Zaliczka'), ('Proforma', 'Proforma'), ('Zamowienie', 'Zamówienie'), ('Faktura', 'Faktura'), ('Korekta', 'Korekta'), ('Nota', 'Nota'), ('Polisa', 'Polisa'), ('Duplikat', 'Duplikat'), ('Inny', 'Inny')], default='', max_length=100, verbose_name='Rodzaj dokumentu'),
        ),
    ]
