# Generated by Django 3.1.3 on 2021-02-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0037_auto_20210221_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienie',
            name='data_dost',
            field=models.DateField(blank=True, null=True, verbose_name='Data dostawy'),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='data_fv',
            field=models.DateField(blank=True, null=True, verbose_name='Data faktury'),
        ),
    ]
