# Generated by Django 3.1.3 on 2021-08-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0041_auto_20210808_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienie',
            name='nr_dok3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nr FV rozliczającej'),
        ),
    ]
