# Generated by Django 3.1.3 on 2021-10-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0042_auto_20210809_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrsde',
            name='nazwa_id',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='ID Nazwa'),
        ),
    ]
