# Generated by Django 3.1.3 on 2021-12-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0043_nrsde_nazwa_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='rokk',
            field=models.IntegerField(default=0, verbose_name='Rok kalendarzowy'),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='rok',
            field=models.IntegerField(default=0, verbose_name='Rok wg SDE'),
        ),
    ]
