# Generated by Django 3.1.3 on 2021-12-05 15:06

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0044_auto_20211204_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrsde',
            name='sum_pcash',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Suma koszty gotówkowe poprzedni rok'),
        ),
        migrations.AddField(
            model_name='nrsde',
            name='sum_pcash_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='nrsde',
            name='sum_pdirect',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Suma koszty bezpośrednie poprzedni rok'),
        ),
        migrations.AddField(
            model_name='nrsde',
            name='sum_pdirect_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
    ]
