# Generated by Django 3.1.3 on 2021-12-15 17:57

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0047_auto_20211208_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrmpk',
            name='b_d',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Bez daty'),
        ),
        migrations.AddField(
            model_name='nrmpk',
            name='b_d_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
    ]
