# Generated by Django 3.1.3 on 2022-01-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0048_auto_20211215_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nrmpk',
            name='rok',
            field=models.IntegerField(default=2022, verbose_name='Rok Nr MPK'),
        ),
        migrations.AlterField(
            model_name='nrsde',
            name='rok',
            field=models.IntegerField(default=2022, verbose_name='Rok Nr SDE'),
        ),
        migrations.AlterField(
            model_name='nrsde',
            name='rokk',
            field=models.IntegerField(default=2022, verbose_name='Rok kal Nr SDE'),
        ),
    ]
