# Generated by Django 3.1.3 on 2022-03-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0050_auto_20220107_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrsde',
            name='stoisko',
            field=models.CharField(blank=True, max_length=500, verbose_name='Stoisko'),
        ),
        migrations.AlterField(
            model_name='nrsde',
            name='opis',
            field=models.CharField(blank=True, max_length=500, verbose_name='Opis'),
        ),
    ]
