# Generated by Django 3.1.3 on 2022-06-14 05:52

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0053_auto_20220612_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienie',
            name='nr_dok1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nr proformy'),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='nr_dok2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nr zaliczki'),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='zal1',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Proforma'),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='zal2',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Zaliczka'),
        ),
    ]
