# Generated by Django 3.1.3 on 2022-07-14 20:58

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0054_auto_20220614_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrsde',
            name='sum_pre_del',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Premie i delegacje'),
        ),
        migrations.AddField(
            model_name='nrsde',
            name='sum_pre_del_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
    ]
