# Generated by Django 3.1.3 on 2022-10-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0055_auto_20220714_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrsde',
            name='pow_pietra',
            field=models.IntegerField(default=0, verbose_name='Powierzchnia piętra'),
        ),
        migrations.AddField(
            model_name='nrsde',
            name='pow_stoisko',
            field=models.IntegerField(default=0, verbose_name='Powierzchnia stoiska'),
        ),
    ]
