# Generated by Django 3.1.3 on 2023-01-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0060_auto_20221218_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nrmpk',
            name='rok',
            field=models.IntegerField(default=2023, verbose_name='Rok Nr MPK'),
        ),
        migrations.AlterField(
            model_name='nrsde',
            name='rok',
            field=models.IntegerField(default=2023, verbose_name='Rok Nr SDE'),
        ),
        migrations.AlterField(
            model_name='nrsde',
            name='rokk',
            field=models.IntegerField(default=2023, verbose_name='Rok kal Nr SDE'),
        ),
    ]
