# Generated by Django 3.1.3 on 2023-01-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0061_auto_20230101_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrmpk',
            name='lsde',
            field=models.BooleanField(default=False, verbose_name='Lista dla SDE'),
        ),
    ]
