# Generated by Django 3.1.3 on 2023-05-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0065_auto_20230402_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nrsde',
            name='pm',
            field=models.CharField(blank=True, choices=[('Agnieszka Skóra', 'Agnieszka Skóra'), ('Julia Królak', 'Julia Królak'), ('Agnieszka Kaźmierska', 'Agnieszka Kaźmierska'), ('Patryk Chodecki', 'Patryk Chodecki'), ('Dariusz Kaczmarek', 'Dariusz Kaczmarek'), ('Łukasz Jerzmanowski', 'Łukasz Jerzmanowski'), ('Michał Ogrzewalski', 'Michał Ogrzewalski'), ('Marzena Michalska', 'Marzena Michalska'), ('Łukasz Zaremba', 'Łukasz Zaremba'), ('Joanna Dittmar', 'Joanna Dittmar'), ('Adam Beim', 'Adam Beim'), ('Eryk Przybyłowicz', 'Eryk Przybyłowicz'), ('Małgorzata Świadek', 'Małgorzata Świadek')], default='', max_length=500, verbose_name='Project Manager'),
        ),
    ]
