# Generated by Django 3.1.3 on 2023-06-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0066_auto_20230528_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienie',
            name='rodzaj_plat',
            field=models.CharField(blank=True, choices=[('Faktura', 'Faktura'), ('Proforma', 'Proforma'), ('Zamowienie', 'Zamówienie'), ('Zaliczka', 'Zaliczka'), ('Korekta', 'Korekta'), ('Nota', 'Nota'), ('Polisa', 'Polisa'), ('Duplikat', 'Duplikat'), ('Inny', 'Inny')], default='', max_length=100, verbose_name='Rodzaj dokumentu'),
        ),
    ]
