# Generated by Django 3.1.3 on 2023-07-12 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0067_auto_20230601_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagaSzukania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(default='', max_length=100, verbose_name='Nazwa')),
            ],
            options={
                'verbose_name': 'Flaga szukania',
                'verbose_name_plural': 'Flagi szukania',
            },
        ),
        migrations.AddField(
            model_name='zamowienie',
            name='nip',
            field=models.CharField(default='', max_length=100, verbose_name='NIP'),
        ),
        migrations.AddField(
            model_name='zamowienie',
            name='flaga_sz',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ORDERS.flagaszukania', verbose_name='Flaga wyszukiwania'),
        ),
    ]
