# Generated by Django 3.1.3 on 2023-07-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0068_auto_20230712_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienie',
            name='nip',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='NIP'),
        ),
    ]
