# Generated by Django 3.1.3 on 2023-07-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0069_auto_20230712_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='flagaszukania',
            name='uwagi',
            field=models.CharField(default='', max_length=200, verbose_name='Uwagi'),
        ),
    ]
