# Generated by Django 3.1.3 on 2023-09-17 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0071_nip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nip',
            options={'verbose_name': 'NIP', 'verbose_name_plural': 'NIP-y'},
        ),
    ]
