# Generated by Django 3.1.3 on 2023-09-17 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0072_auto_20230917_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='nip_ind',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ORDERS.nip', verbose_name='NIP'),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='nip',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='NIP1'),
        ),
    ]
