# Generated by Django 5.0 on 2024-01-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0080_alter_flagaszukania_id_alter_nip_id_alter_nrmpk_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nrmpk',
            name='rok',
            field=models.IntegerField(default=2024, verbose_name='Rok Nr MPK'),
        ),
        migrations.AlterField(
            model_name='nrsde',
            name='rok',
            field=models.IntegerField(default=2024, verbose_name='Rok Nr SDE'),
        ),
        migrations.AlterField(
            model_name='nrsde',
            name='rokk',
            field=models.IntegerField(default=2024, verbose_name='Rok kal Nr SDE'),
        ),
    ]
