# Generated by Django 3.1.3 on 2025-04-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0089_auto_20250106_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nrsde',
            name='pm',
            field=models.CharField(blank=True, choices=[('Agnieszka Skóra', 'Agnieszka Skóra'), ('Julia Królak', 'Julia Królak'), ('Karolina Czabaj', 'Karolina Czabaj'), ('Patryk Chodecki', 'Patryk Chodecki'), ('Dariusz Kaczmarek', 'Dariusz Kaczmarek'), ('Łukasz Jerzmanowski', 'Łukasz Jerzmanowski'), ('Michał Ogrzewalski', 'Michał Ogrzewalski'), ('Marzena Michalska', 'Marzena Michalska'), ('Łukasz Zaremba', 'Łukasz Zaremba'), ('Joanna Dittmar', 'Joanna Dittmar'), ('Adam Beim', 'Adam Beim'), ('Eryk Przybyłowicz', 'Eryk Przybyłowicz'), ('Małgorzata Świadek', 'Małgorzata Świadek'), ('Eliza Adamczyk', 'Eliza Adamczyk'), ('Adam Mikołajczyk', 'Adam Mikołajczyk')], default='', max_length=500, verbose_name='Project Manager'),
        ),
    ]
