# Generated by Django 2.2.3 on 2019-07-06 01:39

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delegacja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100, verbose_name='Imię')),
                ('nazwisko', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('targi', models.CharField(max_length=200, verbose_name='Nazwa Targów')),
                ('data_od', models.DateField(default=django.utils.timezone.now, verbose_name='Data od')),
                ('data_do', models.DateField(default=django.utils.timezone.now, verbose_name='Data do')),
                ('kasa_pln', models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='Gotówka [ PLN ]')),
                ('kasa_euro', models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='Gotówka [ € ]')),
                ('kasa_funt', models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='Gotówka [ £ ] ')),
                ('kasa_inna_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar\xa0Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski Nowy')], default='PLN', editable=False, max_length=3)),
                ('kasa_inna', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Gotówka [ Inna ]')),
                ('kasa_karta_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar\xa0Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski Nowy')], default='EUR', editable=False, max_length=3)),
                ('kasa_karta', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=11, verbose_name='Karta [ Kwota ]')),
            ],
            options={
                'verbose_name': 'Delegacja',
                'verbose_name_plural': 'Delegacje',
            },
        ),
    ]
