# Generated by Django 3.1.3 on 2020-11-28 23:55

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegacja',
            name='kasa_inna_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='delegacja',
            name='kasa_karta_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar Amerykański'), ('EUR', 'Euro'), ('CHF', 'Frank Szwajcarski'), ('GBP', 'Funt Brytyjski'), ('PLN', 'Złoty Polski')], default='EUR', editable=False, max_length=3),
        ),
    ]
