# Generated by Django 3.1.3 on 2021-10-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0003_auto_20201228_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegacja',
            name='zrobione',
            field=models.BooleanField(default=False, verbose_name='Wystawione'),
        ),
    ]
