# Generated by Django 3.1.3 on 2022-03-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0007_auto_20220130_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegacja',
            name='lok_targi',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Lokalizacja Targów'),
        ),
        migrations.AlterField(
            model_name='delegacja',
            name='confirm',
            field=models.CharField(choices=[('SKYPE', 'SKYPE'), ('E-MAIL', 'E-MAIL'), ('BEZ POTWIERDZENIA', 'BEZ POTWIERDZENIA')], default='BEZ POTWIERDZENIA', max_length=50, verbose_name='Potwierdzenie'),
        ),
        migrations.AlterField(
            model_name='delegacja',
            name='targi',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nazwa Targów'),
        ),
    ]
