# Generated by Django 3.1.3 on 2022-03-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0008_auto_20220326_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegacja',
            name='cel_wyj',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Cel wyjazdu'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='transport',
            field=models.CharField(choices=[('--', '--'), ('SAMOLOT', 'SAMOLOT'), ('SAMOCHÓD', 'SAMOCHÓD'), ('SAMOCHÓD FIRMO.', 'SAMOCHÓD FIRMO.')], default='--', max_length=50, verbose_name='Środek lokomocji'),
        ),
        migrations.AlterField(
            model_name='delegacja',
            name='lok_targi',
            field=models.CharField(choices=[('--', '--'), ('POLSKA', 'POLSKA'), ('NIEMCY', 'NIEMCY'), ('HISZPANIA', 'HISZPANIA'), ('USA', 'USA')], default='--', max_length=200, verbose_name='Kraj docelowy'),
        ),
    ]
