# Generated by Django 3.1.3 on 2022-03-27 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0009_auto_20220327_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegacja',
            name='imie',
        ),
        migrations.RemoveField(
            model_name='delegacja',
            name='nazwisko',
        ),
        migrations.AddField(
            model_name='delegacja',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='numer',
            field=models.IntegerField(default=0, verbose_name='Numer dokumentu'),
        ),
        migrations.AlterField(
            model_name='delegacja',
            name='transport',
            field=models.CharField(choices=[('--', '--'), ('SAMOLOT', 'SAMOLOT'), ('SAMOCHÓD', 'SAMOCHÓD'), ('SAMOCHÓD FIRMOWY', 'SAMOCHÓD FIRMOWY')], default='--', max_length=50, verbose_name='Środek lokomocji'),
        ),
    ]
