# Generated by Django 3.1.3 on 2022-03-29 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0010_auto_20220327_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegacja',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data zgłoszenia'),
        ),
    ]
