# Generated by Django 3.1.3 on 2022-03-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0011_auto_20220329_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegacja',
            name='lok_targi',
            field=models.CharField(choices=[('POLSKA', 'POLSKA'), ('NIEMCY', 'NIEMCY'), ('HISZPANIA', 'HISZPANIA'), ('USA', 'USA')], default='POLSKA', max_length=200, verbose_name='Kraj docelowy'),
        ),
        migrations.AlterField(
            model_name='delegacja',
            name='transport',
            field=models.CharField(choices=[('SAMOLOT', 'SAMOLOT'), ('SAMOCHÓD', 'SAMOCHÓD'), ('SAMOCHÓD FIRMOWY', 'SAMOCHÓD FIRMOWY'), ('POCIĄG', 'POCIĄG'), ('AUTOBUS', 'AUTOBUS')], default='SAMOLOT', max_length=50, verbose_name='Środek lokomocji'),
        ),
    ]
