# Generated by Django 3.1.3 on 2022-03-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0012_auto_20220330_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegacja',
            name='kasa_dolar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='Gotówka [ $ ] '),
        ),
    ]
