# Generated by Django 3.1.3 on 2022-04-12 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0017_dieta'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegacja',
            name='dc_rozpo',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Data/Czas rozpoczęcia'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='dc_zakon',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Data/Czas zakończenia'),
        ),
    ]
