# Generated by Django 3.1.3 on 2022-04-12 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0018_auto_20220412_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegacja',
            name='dc_rozpo',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='Data/Czas rozpoczęcia'),
        ),
        migrations.AlterField(
            model_name='delegacja',
            name='dc_zakon',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='Data/Czas zakończenia'),
        ),
    ]
