# Generated by Django 3.1.3 on 2022-04-12 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0019_auto_20220412_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegacja',
            name='powrot_kraj',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='Powrót do Kraju'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='przekr_gran',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='Przekr. granicy'),
        ),
    ]
