# Generated by Django 3.1.3 on 2022-04-12 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0020_auto_20220412_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delegacja',
            old_name='data',
            new_name='dataz',
        ),
    ]
