# Generated by Django 3.1.3 on 2022-04-12 23:21

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0021_auto_20220412_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegacja',
            name='dieta_kr',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Dieta krajowa'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='dieta_kr_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='dieta_razem',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Dieta razem'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='dieta_razem_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='dieta_za',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Dieta zagraniczna'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='dieta_za_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='dieta_za_zl',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Dieta zagraniczna [zł]'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='dieta_za_zl_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='kolacja',
            field=models.IntegerField(default=0, verbose_name='Kolacja'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='obiad',
            field=models.IntegerField(default=0, verbose_name='Obiad'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='sniadanie',
            field=models.IntegerField(default=0, verbose_name='Śniadanie'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='wydatki_sum',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Suma wydatków'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='wydatki_sum_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
    ]
