# Generated by Django 3.1.3 on 2022-04-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0023_auto_20220412_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegacja',
            name='kolacja',
            field=models.IntegerField(default=0, verbose_name='Ilość Kolacji'),
        ),
        migrations.AlterField(
            model_name='delegacja',
            name='obiad',
            field=models.IntegerField(default=0, verbose_name='Ilość Obiadów'),
        ),
        migrations.AlterField(
            model_name='delegacja',
            name='sniadanie',
            field=models.IntegerField(default=0, verbose_name='Ilość Śniadań'),
        ),
    ]
