# Generated by Django 3.1.3 on 2022-05-22 02:31

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0025_pozycja'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozycja',
            name='waluta_pln',
            field=models.BooleanField(default=True, verbose_name='Waluta PLN'),
        ),
        migrations.AlterField(
            model_name='pozycja',
            name='kurs',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Kurs'),
        ),
    ]
