# Generated by Django 3.1.3 on 2022-05-22 05:06

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0026_auto_20220522_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pozycja',
            name='kurs',
        ),
        migrations.RemoveField(
            model_name='pozycja',
            name='kurs_currency',
        ),
        migrations.RemoveField(
            model_name='pozycja',
            name='waluta_pln',
        ),
        migrations.AlterField(
            model_name='pozycja',
            name='kwota_pln',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Kwota PLN'),
        ),
        migrations.AlterField(
            model_name='pozycja',
            name='kwota_waluta',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Kwota'),
        ),
        migrations.AlterField(
            model_name='pozycja',
            name='kwota_waluta_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
    ]
