# Generated by Django 3.1.3 on 2022-05-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0027_auto_20220522_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozycja',
            name='fwaluta',
            field=models.BooleanField(default=True, verbose_name='Flaga waluty'),
        ),
    ]
