# Generated by Django 3.1.3 on 2022-06-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0028_pozycja_fwaluta'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegacja',
            name='czas_opis',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Opis czas'),
        ),
    ]
