# Generated by Django 3.1.3 on 2022-07-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0029_delegacja_czas_opis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegacja',
            name='naz_imie',
            field=models.CharField(choices=[('', ''), ('Agnieszka Skóra', 'Agnieszka Skóra'), ('Julia Królak', 'Julia Królak'), ('Piotr Junik', 'Piotr Junik'), ('Laura Bartkowiak', 'Laura Bartkowiak'), ('Dariusz Kaczmarek', 'Dariusz Kaczmarek'), ('Łukasz Jerzmanowski', 'Łukasz Jerzmanowski'), ('Michał Ogrzewalski', 'Michał Ogrzewalski'), ('Marzena Michalska', 'Marzena Michalska'), ('Łukasz Zaremba', 'Łukasz Zaremba'), ('Joanna Dittmar', 'Joanna Dittmar'), ('Bartosz Ługowski', 'Bartosz Ługowski'), ('Adam Beim', 'Adam Beim'), ('Eryk Przybyłowicz', 'Eryk Przybyłowicz'), ('Małgosia Świadek', 'Małgosia Świadek'), ('Olga Siukova', 'Olga Siukova'), ('Katarzyna Rybak', 'Katarzyna Rybak'), ('Dariusz Grabowski', 'Dariusz Grabowski'), ('Jarosław Stróżyk', 'Jarosław Stróżyk')], default='', max_length=300, verbose_name='Imię i Nazwisko'),
        ),
    ]
