# Generated by Django 3.1.3 on 2022-07-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0030_auto_20220714_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegacja',
            name='silnik_poj',
            field=models.BooleanField(default=True, verbose_name='Pojemność silnika >900cm?'),
        ),
    ]
