# Generated by Django 3.1.3 on 2022-08-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0032_auto_20220730_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegacja',
            name='silnik_poj',
            field=models.BooleanField(default=True, verbose_name='Pojemność silnika > 900cm³ ?'),
        ),
    ]
