# Generated by Django 3.1.3 on 2022-08-03 16:30

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0033_auto_20220803_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegacja',
            name='nocleg_ilosc',
            field=models.IntegerField(default=0, verbose_name='Ilość noclegów'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='nocleg_kr',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Nocleg krajowa'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='nocleg_kr_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='nocleg_za',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Nocleg zagraniczna'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='nocleg_za_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='nocleg_za_zl',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Nocleg zagraniczna [zł]'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='nocleg_za_zl_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
    ]
