# Generated by Django 3.1.3 on 2022-08-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0034_auto_20220803_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegacja',
            name='nocleg_ilosc',
        ),
        migrations.AddField(
            model_name='delegacja',
            name='nocleg_ilosc_kr',
            field=models.IntegerField(default=0, verbose_name='Ilość noclegów kraj'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='nocleg_ilosc_za',
            field=models.IntegerField(default=0, verbose_name='Ilość noclegów zagrani.'),
        ),
    ]
