# Generated by Django 3.1.3 on 2022-08-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0035_auto_20220803_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegacja',
            name='km_ilosc',
            field=models.IntegerField(default=0, verbose_name='Ilość kilometrów'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='koszt_paliwo_kr',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='Koszt paliwa kraj'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='koszt_paliwo_za',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='Koszt paliwa świat'),
        ),
        migrations.AlterField(
            model_name='delegacja',
            name='nocleg_ilosc_za',
            field=models.IntegerField(default=0, verbose_name='Ilość noclegów zagranicznych'),
        ),
    ]
