# Generated by Django 3.1.3 on 2022-08-05 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0040_auto_20220804_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegacja',
            name='do_firmy',
        ),
        migrations.RemoveField(
            model_name='delegacja',
            name='do_firmy_currency',
        ),
        migrations.RemoveField(
            model_name='delegacja',
            name='do_pracownika',
        ),
        migrations.RemoveField(
            model_name='delegacja',
            name='do_pracownika_currency',
        ),
        migrations.RemoveField(
            model_name='delegacja',
            name='lacznie_koszty',
        ),
        migrations.RemoveField(
            model_name='delegacja',
            name='lacznie_koszty_currency',
        ),
        migrations.RemoveField(
            model_name='delegacja',
            name='wydatki_prac',
        ),
        migrations.RemoveField(
            model_name='delegacja',
            name='wydatki_prac_currency',
        ),
        migrations.RemoveField(
            model_name='delegacja',
            name='zaliczki_pob',
        ),
        migrations.RemoveField(
            model_name='delegacja',
            name='zaliczki_pob_currency',
        ),
    ]
