# Generated by Django 3.1.3 on 2022-08-05 02:29

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0042_auto_20220805_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegacja',
            name='wydatki_sum_wal',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Suma wydatków'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='wydatki_sum_wal_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='delegacja',
            name='wydatki_sum',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Suma wydatków [PLN]'),
        ),
    ]
