# Generated by Django 3.1.3 on 2022-08-29 17:39

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0044_delegacja_dane_auta'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegacja',
            name='kurs_dataz',
            field=models.DateField(blank=True, null=True, verbose_name='Data notowania zgłoszenie'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='kursz',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Kurs waluty zgłoszenie'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='kursz_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
    ]
