# Generated by Django 3.1.3 on 2022-09-01 18:04

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0045_auto_20220829_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegacja',
            name='data_pobr_zal',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data pobrania zaliczki'),
        ),
        migrations.AlterField(
            model_name='delegacja',
            name='kurs_dataz',
            field=models.DateField(blank=True, null=True, verbose_name='Data notowania zaliczki'),
        ),
        migrations.AlterField(
            model_name='delegacja',
            name='kursz',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Kurs waluty zaliczki'),
        ),
    ]
