# Generated by Django 3.1.3 on 2022-10-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0046_auto_20220901_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegacja',
            name='kasa_inna_currency',
        ),
        migrations.AlterField(
            model_name='delegacja',
            name='kasa_inna',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='Gotówka [ ₣ ] '),
        ),
    ]
