# Generated by Django 3.1.3 on 2022-10-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0047_auto_20221003_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegacja',
            name='kasa_dolar_kurs1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='[ $ ] Kurs 1'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='kasa_dolar_kurs2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='[ $ ] Kurs 2'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='kasa_dolar_pl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='Gotówka [ $ => PLN ]'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='kasa_euro_kurs1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='[ € ] Kurs 1'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='kasa_euro_kurs2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='[ € ] Kurs 2'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='kasa_euro_pl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='Gotówka [ € => PLN ]'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='kasa_funt_kurs1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='[ £ ] Kurs 1'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='kasa_funt_kurs2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='[ £ ] Kurs 2'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='kasa_funt_pl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='Gotówka [ £ => PLN ]'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='kasa_inna_kurs1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='[ $ ] Kurs 1'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='kasa_inna_kurs2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='[ $ ] Kurs 2'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='kasa_inna_pl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='Gotówka [ $ => PLN ]'),
        ),
    ]
