# Generated by Django 3.1.3 on 2022-10-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0048_auto_20221006_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegacja',
            name='kasa_inna_kurs1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='[ ₣ ] Kurs 1'),
        ),
        migrations.AlterField(
            model_name='delegacja',
            name='kasa_inna_kurs2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='[ ₣ ] Kurs 2'),
        ),
        migrations.AlterField(
            model_name='delegacja',
            name='kasa_inna_pl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='Gotówka [ ₣ => PLN ]'),
        ),
    ]
