# Generated by Django 3.1.3 on 2022-10-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0049_auto_20221006_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozycja',
            name='waluta',
            field=models.CharField(blank=True, default='PLN', max_length=10, verbose_name='Waluta'),
        ),
    ]
