# Generated by Django 3.1.3 on 2022-10-16 18:12

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0050_pozycja_waluta'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegacja',
            name='sum_wydatki1',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Suma wydatków 1'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='sum_wydatki1_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='sum_wydatki2',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=11, verbose_name='Suma wydatków 2'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='sum_wydatki2_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='sum_wydatki3',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='GBP', max_digits=11, verbose_name='Suma wydatków 3'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='sum_wydatki3_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='GBP', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='sum_wydatki4',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=11, verbose_name='Suma wydatków 4'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='sum_wydatki4_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='USD', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='sum_wydatki5',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='CHF', max_digits=11, verbose_name='Suma wydatków 5'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='sum_wydatki5_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='CHF', editable=False, max_length=3),
        ),
    ]
