# Generated by Django 3.1.3 on 2022-10-16 21:00

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0051_auto_20221016_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegacja',
            name='dieta_za_2',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=11, verbose_name='Dieta zagraniczna 2'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='dieta_za_2_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='dieta_za_3',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='GBP', max_digits=11, verbose_name='Dieta zagraniczna 3'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='dieta_za_3_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='GBP', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='dieta_za_4',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=11, verbose_name='Dieta zagraniczna 4'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='dieta_za_4_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='USD', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='dieta_za_5',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='CHF', max_digits=11, verbose_name='Dieta zagraniczna 5'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='dieta_za_5_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='CHF', editable=False, max_length=3),
        ),
    ]
