# Generated by Django 3.1.3 on 2022-10-17 11:43

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0052_auto_20221016_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegacja',
            name='podsumowanie1',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Podsumowanie 1'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='podsumowanie1_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='podsumowanie2',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=11, verbose_name='Podsumowanie 2'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='podsumowanie2_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='podsumowanie3',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='GBP', max_digits=11, verbose_name='Podsumowanie 3'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='podsumowanie3_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='GBP', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='podsumowanie4',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=11, verbose_name='Podsumowanie 4'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='podsumowanie4_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='USD', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='podsumowanie5',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='CHF', max_digits=11, verbose_name='Podsumowanie 5'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='podsumowanie5_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='CHF', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='podsumowanie_pl2',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Podsumowanie pl 2'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='podsumowanie_pl2_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='podsumowanie_pl3',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Podsumowanie pl 3'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='podsumowanie_pl3_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='podsumowanie_pl4',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Podsumowanie pl 4'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='podsumowanie_pl4_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='podsumowanie_pl5',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Podsumowanie pl 5'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='podsumowanie_pl5_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
    ]
