# Generated by Django 3.1.3 on 2022-10-22 17:15

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0054_auto_20221017_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegacja',
            name='kurs',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Kurs waluty'),
        ),
        migrations.AlterField(
            model_name='delegacja',
            name='kurs2',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Kurs waluty - rozliczenie 2'),
        ),
        migrations.AlterField(
            model_name='delegacja',
            name='kurs3',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Kurs waluty - rozliczenie 3'),
        ),
        migrations.AlterField(
            model_name='delegacja',
            name='kurs4',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Kurs waluty - rozliczenie 4'),
        ),
        migrations.AlterField(
            model_name='delegacja',
            name='kurs5',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Kurs waluty - rozliczenie 5'),
        ),
        migrations.AlterField(
            model_name='delegacja',
            name='kursz2',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Kurs waluty - pobranie 2'),
        ),
        migrations.AlterField(
            model_name='delegacja',
            name='kursz3',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Kurs waluty - pobranie 3'),
        ),
        migrations.AlterField(
            model_name='delegacja',
            name='kursz4',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Kurs waluty - pobranie 4'),
        ),
        migrations.AlterField(
            model_name='delegacja',
            name='kursz5',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Kurs waluty - pobranie 5'),
        ),
    ]
