# Generated by Django 3.1.3 on 2022-10-22 17:31

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0055_auto_20221022_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegacja',
            name='dieta_za_efd',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Dieta EFD'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='dieta_za_euro',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=11, verbose_name='Dieta zagraniczna [eur]'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='dieta_za_euro_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='dieta_za_not',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='Dieta zagr. notowanie'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='dieta_za_not_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
    ]
