# Generated by Django 3.1.3 on 2022-10-24 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0056_auto_20221020_0020'),
        ('DELEGATIONS', '0057_auto_20221024_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegacja',
            name='nr_sde1',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ORDERS.nrsde', verbose_name='Nr SDE 1'),
        ),
    ]
