# Generated by Django 3.1.3 on 2022-10-24 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0058_delegacja_nr_sde1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delegacja',
            old_name='nr_sde1',
            new_name='nr_sde_1',
        ),
    ]
