# Generated by Django 3.1.3 on 2022-10-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0059_auto_20221024_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegacja',
            name='nr_sde_1',
        ),
        migrations.AddField(
            model_name='delegacja',
            name='kod_sde_targi1',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Kod SDE Targi 1'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='kod_sde_targi2',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Kod SDE Targi 2'),
        ),
    ]
