# Generated by Django 3.1.3 on 2022-10-24 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0060_auto_20221024_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delegacja',
            old_name='różnica_diet_pl',
            new_name='roznica_diet_pl',
        ),
        migrations.RenameField(
            model_name='delegacja',
            old_name='różnica_diet_pl_currency',
            new_name='roznica_diet_pl_currency',
        ),
    ]
