# Generated by Django 3.1.3 on 2022-11-03 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0061_auto_20221024_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegacja',
            name='powrot_kraj',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='Powrót do Kraju [przekr. granicy]'),
        ),
    ]
