# Generated by Django 3.1.3 on 2022-11-03 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0056_auto_20221020_0020'),
        ('DELEGATIONS', '0062_auto_20221103_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegacja',
            name='targi1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample1', to='ORDERS.nrsde'),
        ),
    ]
