# Generated by Django 3.1.3 on 2022-11-03 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ORDERS', '0056_auto_20221020_0020'),
        ('DELEGATIONS', '0065_auto_20221103_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegacja',
            name='kod_sde_targi1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample1', to='ORDERS.nrsde', verbose_name='Kod SDE Targi 1'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='kod_sde_targi2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample2', to='ORDERS.nrsde', verbose_name='Kod SDE Targi 2'),
        ),
    ]
