# Generated by Django 3.1.3 on 2022-11-07 00:18

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0066_auto_20221103_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegacja',
            name='sde_targi1_pln',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='SDE Targi 1 PLN'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='sde_targi1_pln_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='sde_targi2_pln',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=11, verbose_name='SDE Targi 2 PLN'),
        ),
        migrations.AddField(
            model_name='delegacja',
            name='sde_targi2_pln_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
    ]
