# Generated by Django 3.1.3 on 2022-12-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0071_auto_20221218_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegacja',
            name='pobrane_pw',
            field=models.BooleanField(default=False, verbose_name='Wystawiono PW'),
        ),
        migrations.AlterField(
            model_name='delegacja',
            name='zrobione',
            field=models.BooleanField(default=False, verbose_name='Rozliczono'),
        ),
    ]
