# Generated by Django 3.1.3 on 2023-01-20 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('INVOICES', '0022_auto_20230120_2134'),
        ('DELEGATIONS', '0073_auto_20230119_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegacja',
            name='ind_naz_imie',
        ),
        migrations.AddField(
            model_name='delegacja',
            name='osoba',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='INVOICES.osoba', verbose_name='Imię i Nazwisko'),
        ),
        migrations.AlterField(
            model_name='delegacja',
            name='naz_imie',
            field=models.CharField(choices=[('', ''), ('Agnieszka Skóra', 'Agnieszka Skóra'), ('Julia Królak', 'Julia Królak'), ('Agnieszka Kaźmierska', 'Agnieszka Kaźmierska'), ('Patryk Chodecki', 'Patryk Chodecki'), ('Dariusz Kaczmarek', 'Dariusz Kaczmarek'), ('Łukasz Jerzmanowski', 'Łukasz Jerzmanowski'), ('Michał Ogrzewalski', 'Michał Ogrzewalski'), ('Marzena Michalska', 'Marzena Michalska'), ('Łukasz Zaremba', 'Łukasz Zaremba'), ('Joanna Dittmar', 'Joanna Dittmar'), ('Bartosz Ługowski', 'Bartosz Ługowski'), ('Adam Beim', 'Adam Beim'), ('Eryk Przybyłowicz', 'Eryk Przybyłowicz'), ('Małgorzata Świadek', 'Małgorzata Świadek'), ('Monika Stefańska', 'Monika Stefańska'), ('Katarzyna Rybak', 'Katarzyna Rybak'), ('Dariusz Grabowski', 'Dariusz Grabowski'), ('Ivana Martynov', 'Ivana Martynov'), ('Arkadiusz Słupski', 'Arkadiusz Słupski'), ('Jarosław Stróżyk', 'Jarosław Stróżyk')], default='', max_length=300, verbose_name='Imię i Nazwisko'),
        ),
    ]
