# Generated by Django 3.1.3 on 2023-04-02 20:18

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0074_auto_20230120_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegacja',
            name='kasa_karta_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('DKK', 'DKK'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='dieta',
            name='dieta_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('DKK', 'DKK'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='dieta',
            name='nocleg_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('DKK', 'DKK'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='pozycja',
            name='kwota_pln_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('DKK', 'DKK'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='pozycja',
            name='kwota_waluta_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CHF', 'CHF'), ('DKK', 'DKK'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('USD', 'USD')], default='PLN', editable=False, max_length=3),
        ),
    ]
