# Generated by Django 3.1.3 on 2023-12-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0076_auto_20230917_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegacja',
            name='naz_imie',
            field=models.CharField(choices=[('', ''), ('Agnieszka Skóra.', 'Agnieszka Skóra.'), ('Julia Królak', 'Julia Królak'), ('Karolina Czabaj', 'Karolina Czabaj'), ('Patryk Chodecki', 'Patryk Chodecki'), ('Dariusz Kaczmarek', 'Dariusz Kaczmarek'), ('Łukasz Jerzmanowski', 'Łukasz Jerzmanowski'), ('Michał Ogrzewalski', 'Michał Ogrzewalski'), ('Marzena Michalska', 'Marzena Michalska'), ('Łukasz Zaremba', 'Łukasz Zaremba'), ('Joanna Dittmar', 'Joanna Dittmar'), ('Bartosz Ługowski', 'Bartosz Ługowski'), ('Adam Beim', 'Adam Beim'), ('Eryk Przybyłowicz', 'Eryk Przybyłowicz'), ('Małgorzata Świadek', 'Małgorzata Świadek'), ('Monika Stefańska', 'Monika Stefańska'), ('Katarzyna Rybak', 'Katarzyna Rybak'), ('Dariusz Grabowski', 'Dariusz Grabowski'), ('Ivana Martynov', 'Ivana Martynov'), ('Arkadiusz Słupski', 'Arkadiusz Słupski'), ('Jarosław Stróżyk', 'Jarosław Stróżyk'), ('Kateryna Svichkar', 'Kateryna Svichkar')], default='', max_length=300, verbose_name='Imię i Nazwisko'),
        ),
    ]
