# Generated by Django 5.0 on 2024-01-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DELEGATIONS', '0083_alter_delegacja_id_alter_dieta_id_alter_pozycja_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegacja',
            name='numer',
            field=models.CharField(default='', max_length=50, verbose_name='Numer dokumentu'),
        ),
    ]
